### ISSUE TITLE
Compute geometric area of an element

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#1020]
**Is your feature request related to a problem? Please describe.**
The geometric area of an element is needed to implement the bubble correction (Issue #1019)

**Describe the solution you'd like**
To compute the geometric area of an element similar to Tempest Remap's implementation.

- In Tempest Remap, this is done in the function [`CalculateFaceAreas`](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L129), which in turn calls the
    - [`CalculateFaceArea_Concave`](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L2586) function for concave faces, which in turn calls the 
        - [`ConvexifyFace`](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L2639) (which seems to use an external `Triangle` package (+16K LOC!)) and the
    - [`CalculateFaceArea`](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L2620) for convex ones that, in turn, uses
       - [`CalculateFaceAreaQuadratureMethod`](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L2208)
       
Where should all these geometry utilities live? Should we create a separate file in `src/Spaces/`, say `src/Spaces/bubble_utilities.jl`? 

cc: @simonbyrne , @charleskawczynski

**Comment by valeriabarra** [comment]
How to test this? Against a quadrilateral spherical cap (i.e., one patch of a cubed-sphere with 1 horizontal element)?  I need to find resources

**Comment by simonbyrne** [comment]
If you want it to use `SphereDomain`, it will have to live in a later module. The obvious place is `Meshes`, as that is where we break the sphere into quads.

Tests:
 - a panel of the cubed sphere (quadrilateral spherical cap) should be 1/6th of the spherical surface area (by symmetry)
 - the sum of all elements in a panel should equal the total area of the panel

**Comment by simonbyrne** [comment]
See https://lists.osgeo.org/pipermail/proj/2010-September/004998.html for a method for computing the area of a spherical polygon

**Comment by valeriabarra** [comment]
I was thinking to use the `SpectralElementSpace2D` space as input, and from that one, I would have had access to elements via the topology. 

Yes, regarding the test, I had already thought about 1/6 of the surface area of the cubed sphere

**Comment by simonbyrne** [comment]
Questions:
- [`CalculateFaceAreaKarneysMethod`](https://github.com/ClimateGlobalChange/tempestremap/blob/b622790cc993998dff93e038af38d17b786c98b7/src/GridElements.cpp#L2453) doesn't appear to be used, but I would have thought that this is more accurate than quadrature?
- If we increase the order of the polynomial in a `SpectralElementSpace2D`, how fast does the area computation converge? If this works, we can perhaps make a lighter-weight version of the quadrature for computing areas.

**Comment by valeriabarra** [comment]
> * If we increase the order of the polynomial in a `SpectralElementSpace2D`, how fast does the area computation converge? If this works, we can perhaps make a lighter-weight version of the quadrature for computing areas.

I have written up a [gist](https://gist.github.com/valeriabarra/d16a14811a9c86479f10a3f9d36317fa) to compute this. 

For `ne = 4` and `Nq = [2,3,4,5,6,7,8]`, we get:

```julia
julia> for s in 1:length(space)
           @show rel_error[s]
       end
rel_error[s] = 0.06509450907684002
rel_error[s] = 0.0005743819762145022
rel_error[s] = 5.348046615455987e-6
rel_error[s] = 5.056304713342788e-8
rel_error[s] = 4.804261615202816e-10
rel_error[s] = 4.574470073416723e-12
rel_error[s] = 4.5108903926731954e-14
```

**Comment by valeriabarra** [comment]
Based on our conversation, we won't need to triangulate or convexify faces (pheew). We assume that are faces are all convex (we only have quads) and for the correct geometric area computation we can use a high-order quadrature like the regular GLL one we have for quads, with an arbitrary fix order (say 8).
