### ISSUE TITLE
Some Docs improvements

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#1034]
Our ClimaCore.jl documentation needs some improvements, including (but possibly not limited to):

- [x] Better landing page with brief description (right now this is empty)
- [x] Inclusion of "Installation instructions" or "How to" guides
- [x] Resolution (to a good extent, but maybe not entirely) of build Warnings (e.g., "missing docstring"
- [x] Add contributing guides, code of conduct?
- [x] Reshuffle some sections
- [x] Add missing `lib/` entries

**Comment by valeriabarra** [comment]
@sriharshakandala this [image](https://github.com/CliMA/ClimaCore.jl/blob/5a99983e5494032f02f0ec0f43a9bfcbb03437ef/docs/src/api.md?plain=1#L118) is not linked properly in the docs. Do you know the correct path to locate/link it properly?

**Comment by sriharshakandala** [comment]
Yes. This is located at `https://github.com/CliMA/ClimaCore.jl/tree/main/docs/src/assets`

**Comment by valeriabarra** [comment]
> Yes. This is located at `https://github.com/CliMA/ClimaCore.jl/tree/main/docs/src/assets`

Okay, thanks. It needs to be in the upper-level directory to be linked correctly. I am going to fix it.

**Comment by sriharshakandala** [comment]
> > Yes. This is located at `https://github.com/CliMA/ClimaCore.jl/tree/main/docs/src/assets`
> 
> Okay, thanks. It needs to be in the upper-level directory to be linked correctly. I am going to fix it.

Thanks.

**Comment by valeriabarra** [comment]
Does anyone know how to fix these types of warnings: 

![image](https://user-images.githubusercontent.com/39932030/206274372-8cb217d7-1d8e-4c27-89b3-24909509fc80.png)

The build log is not very informative and I checked that the docstring is there. `domain` is defined similarly in the `Meshes` module but there are not warnings there

**Comment by valeriabarra** [comment]
> Does anyone know how to fix these types of warnings:
> 
> ![image](https://user-images.githubusercontent.com/39932030/206274372-8cb217d7-1d8e-4c27-89b3-24909509fc80.png)
> 
> The build log is not very informative and I checked that the docstring is there. `domain` is defined similarly in the `Meshes` module but there are not warnings there

Oh, I've just figured it out. It needed to be properly namespaced in the docstring!

**Comment by valeriabarra** [comment]
Hum... no, that didn't seem to solve the issue (see this [comment](https://github.com/CliMA/ClimaCore.jl/pull/1035#issuecomment-1341645780)).
