### ISSUE TITLE
Simple integration tests/examples cannot be run locally for excessive memory usage

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#1064]
## Describe the bug
I tried to run some integration tests/examples locally on my machine, that I used to run frequently just fine until some time ago (some in September). But now these examples get killed on my machine for running out-of-memory. 

## To Reproduce
From `main`, try to run locally `examples/hybrid/sphere/deformation_flow.jl` or `examples/hybrid/sphere/hadley_circulation.jl`

```julia
julia --project=examples examples/hybrid/sphere/deformation_flow.jl
```

<details><summary>Project</summary>
<p>
Using the `examples` project.

</p>
</details>

## System details

Any relevant system information:
- Julia version: 1.8.3
- operating system: Ubuntu 20.04
- system memory: 16 GB

## Related issues / PRs

I tried to go back in commit history to see when this started to appear, and up until  `5273149` (PR #972  - merged on October 4th), I can get them to run. But the following merged commit, i.e., `1151fca`  (PR #978 - merged same date, later on October 4th) is the one that kills it. So the latter PR seems to be the culprit in the incremented memory usage.

**Comment by simonbyrne** [comment]
Confirming it was the changes in #978 that caused the memory usage increase. It seems to be particularly related to the stencil coefficient calculations. We need an alternative approach to using inlining.

**Comment by bischtob** [comment]
I think this has moved to implementation stage.
