### ISSUE TITLE
Add support for `reduce`-like operations over columns

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#1095]
The ClimaAtmos gravity wave parameterization requires `reduce`-like operations over columns. See

#### `argmin`
Example [here](https://github.com/CliMA/ClimaAtmos.jl/pull/852/commits/42cc8f94615d7df03cb34ef46c81295bacbc703d#diff-b29723104341bb5db4d26360a4b7386ee282d5f2bfb8ccebf57cd171bb504d5fR71-R75)
 - `argmin` is used to find the minimum level index at which a condition is met. That level index is then used to access several variables at that level.
 - That level index is also used to search up the column, level by level, to compute a `wave_forcing`. I believe that this can be reformulated, and replaced, by an interpolation operation, see sketch in https://github.com/CliMA/ClimaAtmos.jl/issues/897#issuecomment-1304851904.

#### more functions
 - I believe that there are more, for example in https://github.com/CliMA/ClimaAtmos.jl/pull/1233

We really need to add support for these pieces before this pattern spreads because it:
 - is gpu-incompatible
 - introduces risks in the form of bugs (unprotected getindex calls with `Int` / `PlusHalf`)
 - and does not consistently handle topography with the rest of the ClimaCore infrastructure (metric terms are not accounted for when using `parent`)

**Comment by charleskawczynski** [comment]
@dennisYatunin , should we close this?

**Comment by dennisYatunin** [comment]
Yup, this was closed by #1903 (and the ClimaAtmos changes were in CliMA/ClimaAtmos.jl#3226).
