### ISSUE TITLE
Add size to parameter space of data layout

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#11]
Some experiments by @vchuravy suggest there are some performance benefits, particularly on the GPU, to having the fast indices (i,j,k and field size) known at compile time. We could do this by adding these sizes to the parameters of the data layout objects.

**Comment by simonbyrne** [comment]
Example: https://gist.github.com/vchuravy/7798cf3902168469777273cf2effeca6

**Comment by jakebolewski** [comment]
We might need to add the 5 tuple size `(Ni, Nj, Nk, Nv, Nh)` to be able to better optimize field access.

**Comment by jakebolewski** [comment]
A benefit of that would be that the packing data / array wouldn't have to actually be an array giving a bit more flexibility there

**Comment by charleskawczynski** [comment]
Just to note: `Nf` is probably not needed in the type space, as it can be statically determined from `S` and `eltype(parent(data::AbstractData))`, using `DataLayouts.typesize`

**Comment by charleskawczynski** [comment]
Closed by #1757

**Comment by charleskawczynski** [comment]
Going to reopen this, as we do still have some type parameters that are only runtime known. This turns out to be important, based on recent benchmarks (#1893).
