### ISSUE TITLE
Test GPU spectral element operators on extruded box and spherical spaces

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#1169]
Test that existing GPU spectral element operators work on extruded spherical spaces.

- It should test both extruded box and sphere
- It should test the common operators (div, grad, curl), and some compositions (e.g. `div.(grad.(x))`)
  - if you hit #1226, then mark the test as broken.

**Comment by simonbyrne** [comment]
I would start with something simple, like e.g.
https://github.com/CliMA/ClimaCore.jl/blob/4b692d374cfe745e338a84631f301911ecc5e723/test/Operators/hybrid/3d.jl#L21-L45

**Comment by valeriabarra** [comment]
> I would start with something simple, like e.g.
> 
> https://github.com/CliMA/ClimaCore.jl/blob/4b692d374cfe745e338a84631f301911ecc5e723/test/Operators/hybrid/3d.jl#L21-L45

Okay the `div` Operator test was added to PR #1224 

How many other operators and composition of operator tests we want to add?
