### ISSUE TITLE
GPU support for extruded spaces on distributed context

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#1170]
Need to make sure that the vertical context is always a `SingletonCommsContext`, and the horizontal should be a `MPICommsContext`.

**Comment by charleskawczynski** [comment]
We're first updating to the latest version of ClimaComms so that we don't write gpu code that is incompatible with the latest update of ClimaComms.

**Comment by simonbyrne** [comment]
Can we call this done?

**Comment by charleskawczynski** [comment]
I'm still working on a PR for this

**Comment by charleskawczynski** [comment]
It's ready for review now
