### ISSUE TITLE
sphere test for shallow water example does not complete

### ISSUE THREAD

**Issue by waywardpidgeon** [CliMA/ClimaCore.jl#1183]
I am running julia in Win 10 version 1.8.5. The shallow_water.jl test example gives an error 
"MethodError: objects of type ClimaCore.Operators.Divergence{()} are not callable". This is with usempi set to either true or false.

I have a problem with admin priv - the uni does not allow this without support staff intervention.

I have attached an image of the output. Thanks - Kevin

![IMG_20230413_085035](https://user-images.githubusercontent.com/85908498/231586096-bd91abcb-be4f-4bbf-a081-1ff0125bd8e3.jpg)

**Comment by simonbyrne** [comment]
@waywardpidgeon thanks for your interest. 

It looks like you've defined `div = ClimaCore.Operators.Divergence()` globally somewhere, which then breaks this line:
https://github.com/CliMA/ClimaCore.jl/blob/main/examples/sphere/shallow_water.jl#L667

We've set up a new repository for the shallow water examples:
https://github.com/CliMA/ClimaShallowWater.jl
which might be easier to use.
