### ISSUE TITLE
Distributed regridding - store local indices in LinearMap

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCore.jl#1191]
**Is your feature request related to a problem? Please describe.**
We want to simplify the implementation of `remap!` by converting unique indices (TR convention) to local indices in `generate_map` and storing then in the `LinearMap` struct. This conversion is currently being done in the remap! function, but the code will be cleaner and a bit faster if we do this just once during setup of the `LinearMap`.

Part of ClimaCoupler SDI [#188](https://github.com/CliMA/ClimaCoupler.jl/issues/188).
PR #1192.

**Describe the solution you'd like**
We currently convert the unique indices (`target_idxs`) using `target_global_elem_lidx` in `remap!`. We will move this conversion to `generate_map`, remove the unique indices ('target_idxs') from `LinearMap`, store the local indices (`target_local_idxs`) in the `LinearMap` struct, and use these indices directly when performing the multiplication in `remap!`.

`source_global_elem_lidx` is not yet implemented for the source indices, but we will add that as part of this issue as well. We will use it to convert source indices analogously to the target indices, described above.

**Potential pitfall**
If we just store the local element indices in `source_local_idxs` and in `target_local_idxs`, their lengths won't agree with that of `weights`.
* Can we use either `target_global_elem_lidx` or `source_global_elem_lidx` to choose only the local elements of the weights returned by TempestRemap and store those in `LinearMap`?
* We may need to wait until the next PR (when we use `MPI.scatter` instead of `MPI.bcast`) to store only the local values
* For now, I'm storing an value of 0 at non-local indices in `source_local_idxs` and `target_local_idxs`

**Additional context**
To keep backwards compatibility with serial spaces, we should return the unique indices unchanged in the case of a serial space. This is important particularly for the source indices, since the source data is still generated on a serial space at this point. This shouldn't be difficult since `target_global_elem_lidx` and `source_global_elem_lidx` are identity mappings for serial spaces, but we should test this feature.

**Comment by LenkaNovak** [comment]
Sounds good! For the last point, do you mean that we could store source-to-target index maps, either local-to-local or global-to-local, generated using functions which are dispatched on the spaces that are passed in?

**Comment by juliasloan25** [comment]
> Sounds good! For the last point, do you mean that we could store source-to-target index maps, either local-to-local or global-to-local, generated using functions which are dispatched on the spaces that are passed in?

For the backwards compatibility with serial spaces, I wasn't talking about the source-to-target index maps yet. I was saying that when we generate the local source and target indices to be stored in `LinearMap`, we should make sure that these are the unchanged unique indices in the serial case.
