### ISSUE TITLE
Test GPU DSS operations on extruded spaces

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#1193]
Test that DSS works on GPUs on extruded spaces.

**Comment by simonbyrne** [comment]
You can add a dss step to the example used in #1169. 

Then maybe https://github.com/CliMA/ClimaCore.jl/blob/e063e694afd962babe526de98dd8794016242853/test/Operators/hybrid/3d.jl#L146-L152 (once FD operators are working).

**Comment by valeriabarra** [comment]
> You can add a dss step to the example used in #1169.

In PR #1232, I added the DSS step to the tests, as per the first part of this comment.

To address the latter part of the comment, are FD operators supported/working now? 
cc: @charleskawczynski
