### ISSUE TITLE
One test failure 

### ISSUE THREAD

**Issue by waywardpidgeon** [CliMA/ClimaCore.jl#1196]
I ran the two tests, runtests.jl and expensive_runtests.jl, for ClimaCore in a Windows 10 environment successfully, with only one error "Test composed stencils" at line 192 in column.jl:
Expression \del . (w .* I.(\theta))
  Expected: BoundsError
  No exception thrown

A brief examination of the code indicates this just means the program "fell out the bottom" without finding where to compute. It relates to issue #1183, but I can't find any occurrence of "div" in the related code. A secti
[runtests.docx](https://github.com/CliMA/ClimaCore.jl/files/11266988/runtests.docx)
on of the output from the Windows Power Shell is attached.
Thanks - waywardpidgeon
[runtests.docx](https://github.com/CliMA/ClimaCore.jl/files/11266993/runtests.docx)

**Comment by waywardpidgeon** [comment]
I used Pkg.test() as suggested and runtests.jl completed successfully
except for FD opts - linsolve which published 56 passes and 4 broken tests.
Part of the output is attached - its runtests2.docx
Thanks - waywardpidgeon

**Comment by simonbyrne** [comment]
Can you paste the output in a comment (quoted by ```)?

**Comment by waywardpidgeon** [comment]
Sorry about the docx output file. I'm on the Julia learning curve still, and now know how to get the history in a more accessible form, but that will have to wait for next time! Oh, I forgot to say I removed the "!" from !Sys.iswindows() on line 13 of runtests.jl (and the corresponding line of expensive_runtests.jl) of course.

**Comment by charleskawczynski** [comment]
Closed by #1206
