### ISSUE TITLE
Positive preserving methods

### ISSUE THREAD

**Issue by Zhengyu-Huang** [CliMA/ClimaCore.jl#1241]
## Describe the bug
In our simulation, to remain positiveness for the tracer, we have
- vertical upwind scheme
- horizontal limiter (require SSP time stepper)

## To Reproduce
We have the following issues
- We still have negative tracer values
- The maximum dt for SSP time stepper and the vertical upwind scheme is small

Debug strategies
- try explicit treatment of the tracer variables (passive tracer)
- test positive preserving for vertical upwind scheme (single column/passive tracer)
- test positive pressing for horizontal limiter (shallow water equation)

**Comment by valeriabarra** [comment]
I don't think the horizontal limiters have anything to do with this. 

@dennisYatunin  and I both tested it and reproduced the original results from the paper. You can see the report [here](https://clima.github.io/ClimaTimeSteppers.jl/dev/dev/report_gen/#Errors-with-a-Limiter). You can see that with high enough horizontal resolution, `h_elem 20`, with SSP333, we reach undershoots that are only of the order of 1.5802e-13

**Comment by Zhengyu-Huang** [comment]
move to ClimaAtmos
