### ISSUE TITLE
Add iterator for real-world fields in test suite

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#1293]
I'd like to add an iterator in TestUtilities that returns real-world fields (orthogonal to the spaces). The idea is that this can be used for testing edge cases (e.g., in unit tests or performance).

The reason this is needed is because, for example, I added and fixed JET tests in https://github.com/CliMA/ClimaCore.jl/pull/1198, but then found that performance was even worse in ClimaAtmos (build [here](https://buildkite.com/clima/climaatmos-ci/builds/10182#01888df6-f0a8-4473-af2c-d4898626fd52)) because the compiler was unable to recurse for the particular field.

It feels like this has happened before, and I think we need a list of real-world fields to use so that we have a better success signal before deploying.

**Comment by simonbyrne** [comment]
Yeah, that seems like a good idea.

**Comment by charleskawczynski** [comment]
I’ve thought about this a bit more, and I think one problem with this is that the result of such an iterator will be type unstable, and so I think having individual convenience constructors is a better long term solution to avoid lots of type unstable tests.
