### ISSUE TITLE
Add dimension objects to support named dimensions with units + metadata for domains

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimaCore.jl#13]
Domains should take labeled dimension objects with optional units for unit conversion between across the model interface.  Named dimensions allow for higher level indexing into model domains and can be passed through to support output formats that adhere to the CF metadata conventions.

Alternatively we could add support for this this as part of the `Domain` constructor and have dimensions is a hidden interface.

**Comment by simonbyrne** [comment]
Would be useful to have some examples for this.
