### ISSUE TITLE
Upgrade to CUDA 11.8

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#1314]
This is needed to fully resolve #1240. CUDA 11.3 support is likely being dropped from CUDA.jl: https://github.com/JuliaGPU/GPUCompiler.jl/pull/467#issuecomment-1587009379

**Comment by maleadt** [comment]
> CUDA 11.3 support is likely being dropped from CUDA.jl:

FWIW, we're not dropping support, just warning about miscompilations when using older hardware. The lower-bound will also be CUDA 11.5.

**Comment by simonbyrne** [comment]
Ah, good to know. Thanks for tackling this, I know it must have been a pain!
