### ISSUE TITLE
FieldVector is incompatible with DiffEq.jl step! function 

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaCore.jl#132]
@LenkaNovak for a minimum working example :).

**Comment by bischtob** [comment]
Hm. I found there to be no issue. Example is [here](https://github.com/CliMA/ClimaCore.jl/blob/ea769c7c38db7c954d6a6e3c90ae4340d709f1b6/examples/column/hydrostatic_with_step.jl#L144).

**Comment by simonbyrne** [comment]
Okay, I'll close this for now. Please re-open if still an issue.
