### ISSUE TITLE
Propertynames for field vector?

### ISSUE THREAD

**Issue by bischtob** [CliMA/ClimaCore.jl#134]
Should the field vector implement a custom `propertynames` function that returns the names of fields stored in it?

**Comment by bischtob** [comment]
This is useful in some places when you want to write generic code that uses fieldvectors.

**Comment by charleskawczynski** [comment]
Here's an [example](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/Turbulence_PrognosticTKE.jl#L552-L609) where we do this in EDMF, and it's called with different variables [here](https://github.com/CliMA/TurbulenceConvection.jl/blob/main/src/Turbulence_PrognosticTKE.jl#L542-L545). I think this would be very useful, too.

**Comment by jakebolewski** [comment]
it isn't lexographically sorted but you can call `propertynames` on fields?

**Comment by jakebolewski** [comment]
Ah you want this for `FieldVector` not fields, I'm not entirely sure `FieldVector` will stick around as an abstraction.
