### ISSUE TITLE
`column_integral_definite!` causes StackOverflow on gpu

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#1376]
`column_integral_definite!` causes a StackOverflow on the gpu due to its function definition:

```julia
function column_integral_definite!(col∫field::Fields.Field, field::Fields.Field)
    Fields.bycolumn(axes(field)) do colidx
        column_integral_definite!(col∫field[colidx], field[colidx])
        nothing
    end
    return nothing
end
```

This is the next issue we're hitting for moisture cases cc @simonbyrne

**Comment by charleskawczynski** [comment]
Seen in https://buildkite.com/clima/climaatmos-ci/builds/11242#018956ac-37ad-466f-8f4b-aef6ee5e1fd8

**Comment by simonbyrne** [comment]
It looks like it is recursively calling itself. We need a version which passes through `hidx`

**Comment by charleskawczynski** [comment]
Yeah, it currently relies on `bycolumn` actually doing something
