### ISSUE TITLE
Add scalar support to FieldVector

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#139]
Not sure the best way to do this, but it should be possible to do something like
```
Y = FieldVector(x=(a=1.0,b=2.0))
``
and do either
```
Y.x = (a=1.0, b=3.0)
```
or 
```
Y.x.b = 3.0
```

**Comment by jakebolewski** [comment]
I thought that this was just supposed to be a wrapper type over created fields for solver support?

**Comment by simonbyrne** [comment]
This is required for the single-column land model.

**Comment by simonbyrne** [comment]
Also could be useful to support nested `FieldVector`s
