### ISSUE TITLE
`Vector` `Field`s don't support `.= constant`

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaCore.jl#1461]
Let `u` be a `Vector` `Field`, e.g., a `Covariant123Vector{Float32}-Field`.
```julia
u .= 0.f0
```
returns
```
ERROR: MethodError: Cannot `convert` an object of type Float32 to an object of type ClimaCore.Geometry.Covariant123Vector{Float32}

Closest candidates are:
  convert(::Type{AT}, ::ClimaCore.Geometry.AxisTensor) where AT<:ClimaCore.Geometry.AxisTensor
   @ ClimaAtmos ~/repos/all/ClimaAtmos.jl/src/solver/types.jl:460
  convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray
   @ LinearAlgebra ~/.julia/juliaup/julia-1.9.3+0.x64.linux.gnu/share/julia/stdlib/v1.9/LinearAlgebra/src/factorization.jl:59
  convert(::Type{AA}, ::ImageFiltering.KernelFactors.ReshapedOneD) where AA<:AbstractArray   @ ImageFiltering ~/.julia/packages/ImageFiltering/QW8Jn/src/kernelfactors.jl:110
  ...

Stacktrace:
 [1-6] ⋮ internal
     @ ClimaCore.DataLayouts, Unknown
   [7] materialize!(dest::Field{} (trunc disp), bc::Base.Broadcast.Broadcasted{Base.Broadcast.DefaultArrayStyle{0}, Nothing, …})
     @ Base.Broadcast ./broadcast.jl:881
Use `err` to retrieve the full stack trace.
```

I see why this is happening (the `eltype` of a `Vector` `Field` is a `Vector`, not a `Float32`), but I think that when the right-hand side of `.=` is a scalar, the operation is well defined and it would be reasonable that the scalar is broadcasted over the components and the elements. This would be particularly useful to zero-out a `Vector` `Field`.

EDIT:
```
julia> a = [[2, 3], [2, 3], [3, 2]]
3-element Vector{Vector{Int64}}:
 [2, 3]
 [2, 3]
 [3, 2]

julia> a .= 1
ERROR: MethodError: Cannot `convert` an object of type Int64 to an object of type Vector{Int64}
```
So, I guess this follows the same pattern as Julia.

**Comment by simonbyrne** [comment]
Eh: it makes sense for zero, but not much else.

**Comment by Sbozzolo** [comment]
> Eh: it makes sense for zero, but not much else.

I would like to set to `0`, `-Inf`, and `+Inf` so that I can reset my accumulators for `average`, `max`, and `min`.

**Comment by simonbyrne** [comment]
Ah ok. In that case you can use `fill!(parent(field), ...)`.

**Comment by Sbozzolo** [comment]
Would this also work for if the element were a scalar? (Or do I have to specifically check that we have vectors)

**Comment by simonbyrne** [comment]
no, that works for any field (`parent(field)` just gets the underlying array).

**Comment by Sbozzolo** [comment]
Perfect!
