### ISSUE TITLE
FieldVector broadcast inference failure

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#1465]
Reproducer:

```julia
import ClimaCore
import ClimaCore.Spaces as Spaces
import ClimaCore.Fields as Fields
using StaticArrays
include(
    joinpath(pkgdir(ClimaCore), "test", "TestUtilities", "TestUtilities.jl"),
)
import .TestUtilities as TU

function foo!(args)
    (; residual, temp, dt,a_imp, Ui) = args
    i=1
    @. residual = temp + dt * a_imp[i, i] * residual - Ui
    return nothing
end

FT = Float32
cspace = TU.CenterExtrudedFiniteDifferenceSpace(FT);
Yc = fill((;a=FT(0)),cspace);
args = (;
    residual=Fields.FieldVector(;c=Yc),
    temp=Fields.FieldVector(;c=Yc),
    a_imp=SMatrix{1,1}(rand(1,1)),
    Ui=Fields.FieldVector(;c=Yc),
    dt = 1.0,
);
foo!(args)

using JET
JET.@test_opt foo!(args)

```

**Comment by charleskawczynski** [comment]
I think this is blocking us from using the latest ClimaTimeSteppers (which is OOMing)

**Comment by charleskawczynski** [comment]
Strangely

```julia
using JET; v = Int[1,7,3,4,1]; JET.@test_opt sort!(v)
using Revise; include("../cc_bc_inf.jl")
```
(where `cc_bc_inf.jl` is the MWE above) passes. Something very strange is going on with `sort!(::Vector{Int})`.. cc @simonbyrne

**Comment by charleskawczynski** [comment]
```julia
julia> versioninfo()
Julia Version 1.9.3
Commit bed2cd540a1 (2023-08-24 14:43 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
```

**Comment by charleskawczynski** [comment]
Boiled down to:
```julia
using BlockArrays
shape1 = (BlockArrays._BlockedUnitRange((2,)),);
shape2 = (BlockArrays._BlockedUnitRange((2,)),);
Base.Broadcast._bcs(shape1, shape2)
@code_warntype Base.Broadcast._bcs(shape1, shape2)
```

**Comment by charleskawczynski** [comment]
Opened https://github.com/JuliaArrays/BlockArrays.jl/issues/310

**Comment by simonbyrne** [comment]
How is this different than what you were doing before? Why did it only appear now?

**Comment by charleskawczynski** [comment]
The only difference is that we do it more times because the stage loop is unrolled.

That said, I'm beginning to think this is not the issue. One odd thing I found is that this inference failure disappears if we change the broadcast expression from

```julia
@. residual = temp + dt * a_imp[i, i] * residual - Ui
```
to
```julia
@. residual = temp + dt * a_imp[i, i] * residual
```
(removing any other fieldvector from the RHS has the same impact). So, it seems like the code path is changing based on on the number of terms we have. I tried running a single step with this change, and the compiler still  SO'd when compiling `step_u!`. So, I don't think this is the issue. Still digging into what is wrong. I'm changing gears by commenting / uncommenting code to try and identify the issue.

**Comment by charleskawczynski** [comment]
It turns out that this is just due to https://github.com/JuliaArrays/BlockArrays.jl/issues/310. I'm hoping that https://github.com/JuliaArrays/BlockArrays.jl/pull/313 is merged, which fixes this issue. Basically, anytime we have more than one FieldVector on the RHS of a broadcast expression, `Base.Broadcast.check_broadcast_axes` is called, which leads to https://github.com/JuliaArrays/BlockArrays.jl/issues/310.
