### ISSUE TITLE
Add support for hypsography in `interpolate_array`

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaCore.jl#1488]
As the docstring for `interpolate_array` mentions:
```julia
!!! note
    Hypsography is not currently handled correctly.
```
The reason for this is in the call `velem = Meshes.containing_element(vert_mesh, zcoord)` in the `interpolate_slab_level_function`. With topography, this function looks up the `zcoord` above the local surface, not the `zcoord` above the sea level.

There's two valid ways to approach this problem (both required): 
- interpret `zcoord` as level. In this case, the `ClimaAtmos` NetCDF writer will have to handle this accordingly and output an elevation map
- find the correct vertical element that contains the coordinate (and return `NaN` or a fill value when not existing).

**Comment by simonbyrne** [comment]
For option 1, it should be written as http://cfconventions.org/Data/cf-conventions/cf-conventions-1.10/cf-conventions.html#atmosphere-hybrid-height-coordinate
