### ISSUE TITLE
Define indefinite column integrals for arbitrary functions

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#1492]
ClimaAtmos currently uses

```julia
    prob = SciMLBase.ODEProblem(dp_dz, p_0, (FT(0), z_max))
    return SciMLBase.solve(
        prob,
        ODE.Tsit5(),
        reltol = 10eps(FT),
        abstol = 10eps(FT),
    )
```
to compute a vertical indefinite integral. We currently only need this for initialization, and https://github.com/CliMA/ClimaAtmos.jl/pull/2183 implements this in a way that seems to work (MSE table changes are small). We could start by porting that over to ClimaCore and adding unit tests. Next (if we need) we could make this work on the GPU, which I think shouldn't be too difficult (it may work already as I've followed a similar pattern used for the other indefinite integral on fields).

**Comment by simonbyrne** [comment]
You added something in https://github.com/CliMA/ClimaCore.jl/pull/1380: is there anything else we need?

**Comment by charleskawczynski** [comment]
Not for ClimaAtmos to run, as far as I can tell (other than a unit test)
