### ISSUE TITLE
Add GPU support for horizontal limiters

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#1493]

**Comment by charleskawczynski** [comment]
To confirm, is the plan to implement the exact same version of what we currently have, but to be GPU compatible?

**Comment by charleskawczynski** [comment]
This item is under "implement water borrowing and test in baroclinic wave". This issue needs more context and information-- I've put it on hold for now.

**Comment by charleskawczynski** [comment]
I've confirmed that we just want to port the existing limiters to the gpu, for now.
