### ISSUE TITLE
Add `min_nodal_distance` / `mean_nodal_distance`

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#1580]
It would be useful if we provided a function that computes the minimum / and or average (e.g., `reduced_nodal_distance`) for hyperdiffusion, which usually has a grid-spacing-aware coefficient.

cc @szy21

**Comment by simonbyrne** [comment]
We have https://github.com/CliMA/ClimaCore.jl/pull/739, which is sort of an "average nodal distance". There was some discussion on the name, but I can update the PR.

**Comment by charleskawczynski** [comment]
Ok, I think we'll want horizontal and vertical split out, but it still looks like there's some useful pieces there.

**Comment by simonbyrne** [comment]
It is currently horizontal only: I'll update the name.
