### ISSUE TITLE
buoyancy_gradients parameter size too large

### ISSUE THREAD

**Issue by juliasloan25** [CliMA/ClimaCore.jl#1597]
## Describe the bug
When testing coupled runs on GPU from ClimaCoupler, [this call](https://github.com/CliMA/ClimaAtmos.jl/blob/main/src/prognostic_equations/gm_sgs_closures.jl#L35C1-L50C6) to `buoyancy_gradients` in ClimaAtmos fails with `'Kernel parameter size larger than 4352 bytes'` on central, but not on clima. This method is called as part of the cloud fraction model initialization.

failing run on ClimaCoupler buildkite: https://buildkite.com/clima/climacoupler-ci/builds/2435#018d33c6-a5d8-4589-acbb-e49be43c89b9

cc @charleskawczynski 

This is the space being used in the failing run:
`julia> atmos_sim.domain
(center_space = CenterExtrudedFiniteDifferenceSpace:
  context: SingletonCommsContext using CUDADevice
  horizontal:
    mesh: 4×4×6-element EquiangularCubedSphere of SphereDomain: radius = 6.371e6
    quadrature: 4-point Gauss-Legendre-Lobatto quadrature
  vertical:
    mesh: 10-element IntervalMesh of IntervalDomain: z ∈ [0.0,30000.0] (:bottom, :top), face_space = FaceExtrudedFiniteDifferenceSpace:
  context: SingletonCommsContext using CUDADevice
  horizontal:
    mesh: 4×4×6-element EquiangularCubedSphere of SphereDomain: radius = 6.371e6
    quadrature: 4-point Gauss-Legendre-Lobatto quadrature
  vertical:
    mesh: 10-element IntervalMesh of IntervalDomain: z ∈ [0.0,30000.0] (:bottom, :top))`

## To Reproduce
Ideally a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):

```julia
# some code here
```

Or even better, add it as a unit test, and open pull request.

<details><summary>Project</summary>
<p>
If not using the `examples` project:
```
paste your Project.toml here.
```
```
paste your Manifest.toml here.
```

</p>
</details>

**Comment by charleskawczynski** [comment]
Basically, this is a dup (or revival of) #1226.

**Comment by simonbyrne** [comment]
Upgrading to CUDA.jl 5.2 should include this which now gives more information:
https://github.com/JuliaGPU/CUDA.jl/pull/2180#issuecomment-1877433662

**Comment by juliasloan25** [comment]
in another buildkite job the same run passed: https://buildkite.com/clima/climacoupler-ci/builds/2449#018d38b1-43e0-40b9-b349-c72ba60f59d3

**Comment by charleskawczynski** [comment]
I believe improvements in this kernel have fixed the issue. @juliasloan25, please feel free to reopen if this issue pops back up.
