### ISSUE TITLE
Add simplified unit tests for hydrostatic balance in the vertical for FD, hybrid 1DX, 2DX function spaces

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimaCore.jl#166]
cc @bischtob

**Comment by jakebolewski** [comment]
We can test these with a tendency evaluation and don't need the full ODE machinery.

**Comment by bischtob** [comment]
cc @LenkaNovak , @valeriabarra, @kmdeck

**Comment by jakebolewski** [comment]
https://github.com/CliMA/ClimaCore.jl/blob/7ce6d0d89bc934eb0da8a9486ff27134a681a885/examples/hybrid/bubble.jl

**Comment by szy21** [comment]
Do we still need this? @akshaysridhar has been testing hydrostatic balance in the box setup with and without topography. I don't think it has been written as a unit test though.
