### ISSUE TITLE
Deep atmosphere might have some bugs

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaCore.jl#1727]
In the following, I try to solve the horizontal heat equation on a Little-Prince planet with radius 1 and atmsphere heigth of 1. Nothing happens on the vertical direction.

Even switching `deep = true`, the results seem wrong. The results converge to a qualitatevely correct solution when I increase the radius.
```julia
    FT = Float64
    dt = 0.01

    radius = FT(1)
    nelems = 50
    npoly = 3

    height = 1
    zelem = 2

    vertdomain = ClimaCore.Domains.IntervalDomain(
        ClimaCore.Geometry.ZPoint(FT(0)),
        ClimaCore.Geometry.ZPoint(FT(height));
        boundary_names = (:bottom, :top),
    )
    vertmesh = ClimaCore.Meshes.IntervalMesh(vertdomain; nelems = zelem)
    vertgrid = ClimaCore.Grids.FiniteDifferenceGrid(vertmesh)

    horzdomain = ClimaCore.Domains.SphereDomain(radius)
    horzmesh = ClimaCore.Meshes.EquiangularCubedSphere(horzdomain, nelems)
    horztopology = ClimaCore.Topologies.Topology2D(ClimaCore.ClimaComms.context(), horzmesh)
    horzquad = ClimaCore.Spaces.Quadratures.GLL{npoly + 1}()
    horzgrid = ClimaCore.Grids.SpectralElementGrid2D(horztopology, horzquad)

    grid = ClimaCore.Grids.ExtrudedFiniteDifferenceGrid(horzgrid, vertgrid, deep = true)
    space = ClimaCore.Spaces.CenterExtrudedFiniteDifferenceSpace(grid)

    # Gaussian perturbation

    (; lat, long) = ClimaCore.Fields.coordinate_field(space)
    φ_gauss = @. exp(-(lat^2 + long^2)/(200))

    Y₀ = ClimaCore.Fields.FieldVector(; my_var = copy(φ_gauss))
    t0 = zero(FT)
    t_end = FT(10)

    diverg = ClimaCore.Operators.WeakDivergence()
    grad = ClimaCore.Operators.Gradient()

    function T_exp!(fU_exp, U, p, t)
        @. fU_exp.my_var = diverg(grad(U.my_var))
    end

    function dss!(state, _, t)
        ClimaCore.Spaces.weighted_dss!(state.my_var)
    end

    prob = DiffEqBase.ODEProblem(
        ClimaTimeSteppers.ClimaODEFunction(T_exp! = T_exp!, dss! = dss!),
        Y₀,
        (t0, t_end),
        nothing,
    )
    algo = ClimaTimeSteppers.IMEXAlgorithm(ClimaTimeSteppers.ARS343(), ClimaTimeSteppers.NewtonsMethod())
    integrator = SciMLBase.init(prob, algo; dt, saveat = dt)
```
Initial data:
![image](https://github.com/CliMA/ClimaCore.jl/assets/9167485/ab997409-5cfe-451b-ad32-778870bf4c1c)

First step:
![image](https://github.com/CliMA/ClimaCore.jl/assets/9167485/967c1d5d-84f0-4bf8-8b5c-cae41cbba81f)

```julia
extrema(integrator.u.my_var)
(5.008401127052524e-71, 34.5302964027676)
```
Also shows that something is off

**Comment by akshaysridhar** [comment]
The diffusive Courant number for the problem as it is currently set up is O(10) - this suggests that the blow-up issue should be reproducible even on a `SpectralElement2D` (non-extruded configuration, akin to a `z=0` correction in the deep-sphere metrics). For the current timestep size, I tried relaxing the element count to 10, i.e. ~courant 0.4; the outcome of solve! is reasonable :   

<img width="598" alt="Screenshot 2024-05-16 at 5 22 46 PM" src="https://github.com/CliMA/ClimaCore.jl/assets/43710045/e2bf2f27-5fee-43ad-a65b-1b1323215aa6">

There may yet be issues with the metrics, I'll check this as well.
