### ISSUE TITLE
PlusHalf name is not intuitive

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#178]
One thing I recently realized is that the `PlusHalf` name will be _extremely_ counter intuitive to the EDMF team, because SCAMPy used `full` and `half` for faces and cell centers respectively, and now this convention, where `PlusHalf` is used for cell faces will effectively swap them. Also, the choice to use `PlusHalf` for faces seems arbitrary--it just so happens that cell faces occur first, so I understand the reasoning as to why this was chosen. But wouldn't it be more clear/intuitive if we just use names `FaceIndex` / `CenterIndex`?

**Comment by jakebolewski** [comment]
Doesn't that just mean that Scampy didn't use the convention used everywhere in the literature?

**Comment by simonbyrne** [comment]
I think when we looked at the literature the convention was that 1/2 levels typically referred to faces

**Comment by szy21** [comment]
I think it is correct that Scampy didn't use the convention. `Face` or `Center` does sound more clear to me, though.

**Comment by simonbyrne** [comment]
Simmons and Burridge seems to use this:
<img width="425" alt="Screen Shot 2021-09-14 at 9 50 34 AM" src="https://user-images.githubusercontent.com/1692009/133300335-92fc145a-8236-4073-ad99-1decd09cb36c.png">

**Comment by jakebolewski** [comment]
It would be good to look at how it is used in the stencils before offering suggestions.  Generally this shouldn't be user facing at all?

**Comment by simonbyrne** [comment]
> But wouldn't it be more clear/intuitive if we just use names `FaceIndex` / `CenterIndex`?

The point of the `PlusHalf` is that it makes it easier to refer to neighboring values: i.e. that if I'm at cell center `i`, I know that the neighbouring faces are `i-half` and `i+half`.

**Comment by jakebolewski** [comment]
Yes, it also generalizes to higher order stencils

**Comment by valeriabarra** [comment]
> I think when we looked at the literature the convention was that 1/2 levels typically referred to faces

Yes, this was my experience in my PhD research staggered FD scheme. 
I would say as long as we document it, it should be clear. Also, we could support both `PlusHalf` and alias it as Charlie suggested `FaceIndex` to make it explicit?

**Comment by valeriabarra** [comment]
> Also, the choice to use `PlusHalf` for faces seems arbitrary--it just so happens that cell faces occur first, so I understand the reasoning as to why this was chosen.

I don't think it's that arbitrary after all. Defining cell centers by integer indices allows to support both staggered and non-staggered grids (obviously non-staggered grids would only have integer indices).

**Comment by charleskawczynski** [comment]
> I know that the neighbouring faces are i-half and i+half. I don't see how FaceIndex/CenterIndex would help that.

I see, that's a good argument for the use of `PlusHalf`. Maybe we can just write custom error messages that use `Face` data and `Center` data terminology to help users debug?

**Comment by jakebolewski** [comment]
I have a nascent branch that i need to update for better error messages, closing as part of #52
