### ISSUE TITLE
Composing operator with  Ref

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#189]
```julia
Ic2f = Operators.InterpolateC2F(
    top = Operators.Extrapolate(),
    bottom = Operators.Extrapolate(),
)
# h is a center-valued scalar field
c = Geometry.Cartesian3Vector(1.0)
Ic2f.(h) .* Ref(c) # causes an error
Ic2f.(h .* Ref(c)) # causes an error
```

**Comment by jakebolewski** [comment]
You can't have `Ref()` in the broadcasted operation right?  it has to be pulled out so it is not syntactically part of the expression

**Comment by simonbyrne** [comment]
It works for horizontal operators, just not the finite difference ones.

**Comment by jakebolewski** [comment]
It's because we overload getindex calls with `getidx`.  I added unboxing support for Ref in getidx calls https://github.com/CliMA/ClimaCore.jl/blob/main/src/Operators/finitedifference.jl#L1642 on the latest main branch but I don't think it would solve the syntax issue.

**Comment by jakebolewski** [comment]
This is fixed on `main` with the link above:
```
julia> c = 0.5
0.5

julia> Ic2f.(c_ones) .* Ref(c) # causes an error
Float64-valued Field:
  [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0]

julia> Ic2f.(c_ones .* Ref(c)) # causes an error
Float64-valued Field:
  [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.0]
```

**Comment by jakebolewski** [comment]
I didn't notice that you were not trying to broadcast the Ref, so you are right the above should be expected to work.
