### ISSUE TITLE
Donwstream test for ClimaCoupler is failing

### ISSUE THREAD

**Issue by Sbozzolo** [CliMA/ClimaCore.jl#1911]
I think the first commit to break the downsteram test is https://github.com/CliMA/ClimaCore.jl/commit/32ec1fd6ec151558a70ffac056b59ca2ee198ee5

Failure:
https://github.com/CliMA/ClimaCore.jl/actions/runs/10065939327/job/27826165985

**Comment by charleskawczynski** [comment]
Yeah, I planned on adding deprecations for the removed constructors. I'll try to do this today.
