### ISSUE TITLE
Look over the rising bubble test case

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCore.jl#203]
**Context**

Currently, we have all the software support for the rising bubble test case, and a prototype [here](https://github.com/CliMA/ClimaCore.jl/blob/main/examples/hybrid/bubble.jl). We need to compare the results with the literature and make sure everything is set up correctly (equations, flux correction, interpolation, etc.)

**Next steps**

- Check whether the flux correction operator in this [PR](https://github.com/CliMA/ClimaCore.jl/pull/200) is correct, write unit tests if necessary
- Run the rising bubble test case with only horizontal and vertical diffusion and with different viscosity. Check whether a larger diffusivity can make the simulation stable.
- Run the rising bubble test case with horizontal hyperdiffusion and vertical flux correction and compare with Paul's results.
- Run the rising bubble test case with horizontal hyperdiffusion and vertical flux correction at different resolutions.
- After eveything is working correcty, move the test case to ClimaAtmos.

**Comment by jakebolewski** [comment]
I don't think this really belongs here, really all this work needs to be moved to the Atmos model.

**Comment by szy21** [comment]
I agree that in the end it should stay in the Atmos model. We just think it might be easier to build on the current example, and after everything is working correctly we can move it to ClimaAtmos.

**Comment by jakebolewski** [comment]
I think partly that is because there is no infrastructure to run tests like
this, it would be good to work on setting that up.

**Comment by szy21** [comment]
Yes, we are working on the infrastructure in ClimaAtmos. We already have the domain and model for the rising bubble test case, but still need some work on the diagnostics. We will move the tests to ClimaAtmos once that is done.

**Comment by jakebolewski** [comment]
I think this can be closed, minus moving stuff over to ClimaAtmos
