### ISSUE TITLE
Add unit tests for CG operators on the sphere

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#220]
- [x] operator and annihilator properties
  - can get closed forms based on spherical harmonics
  - hyperdiffusion and curl
  - add equations to design docs

@jiahe23 implemented some of these for ClimateMachine.jl

**Comment by valeriabarra** [comment]
I think another good test to add would be a Poisson problem so that you test the diffusion operator alone. It is simple, provided you can eliminate the nullspace of the operator in your solver (otherwise a Poisson's problem on a closed domain has a nullspace)

**Comment by valeriabarra** [comment]
#237  and #238 take care of hyperdiffusion and diffusion, respectively. I think we are left with curl. 
Also, do we want to check any annhilator properties? 
Should we just replicate all tests in [test/spectraloperators.jl](https://github.com/CliMA/ClimaCore.jl/blob/main/test/spectraloperators.jl) for the cubed-sphere?

**Comment by szy21** [comment]
@valeriabarra @jiahe23 Would it be useful to test vector hyperdiffusion as well, like [here](https://github.com/CliMA/ClimaCore.jl/blob/d6e480dbce58ff420820de4e511619afdf7ed9bb/test/spectraloperators.jl#L299)?
