### ISSUE TITLE
Distribute ClimaCore

### ISSUE THREAD

**Issue by kpamnany** [CliMA/ClimaCore.jl#228]
- Partition the mesh -- Hilbert SFC partitioner can be adapted from ClimateMachine -- when setting up a distributed topology.
- Expand interfaces for local/global -- `nlocalelems`, `interior_faces`, etc.
- Build communication module that also manages buffers to abstract over MPI/SharedArrays/Gasp.
- Use communication module in:
  - DSS
  - Field operations (`LinearAlgebra.ldiv!`, etc.)
  - Boundary fluxes (not yet defined)

DSS communication:
- Use ghost elements as in ClimateMachine.
- Neighbor exchange relevant ghost element nodal values via communication model interface; five distinct steps:
  - Ready-to-receive.
  - Start-sending.
  - Complete-receiving.
  - Complete-sending.
  - Global-synchronization.

**Comment by simonbyrne** [comment]
Aim to support initially:
- SharedArrays on a single memory space (basically just for synchronization)
- MPI Isend/Irecv (with optional double buffering for GPU support)
Future options:
- GASP / MPI One-sided
- MPI Topologies / Graph collectives (`MPI_INEIGHBOR_ALLTOALL`)
- [NCCL](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/index.html)

Basic communication interface:
- start buffer exchange
- end buffer exchange
- progress

# Topology API
- Mesh: lightweight object common to all processes
- Each process has its own topology: this is constructed by the partitioner

Key things
a. iterator over local elements
b. iterator over faces (try to keep terminology consistent: see if there are better names)
  - interior faces (both elements on same process)
  - neighbor faces (across process boundary)
  - boundary faces (boundary of the actual mesh)
c. iterator over vertices?
d. iterator shared nodes / dofs?
  - interior-only nodes (all shared elements are on same process)
    - nested iterator over (elem, nodeidx) where nodeidx = 1:Nq^2
  - neighbor nodes (at least one shared element on remote process)
    - if on remote, element = negative process number, nodeidx = buffer index
![Whiteboard 3 -01](https://user-images.githubusercontent.com/1692009/140157266-faad06f4-0a83-4cad-9f56-9292bf7c1ae8.png)

**Comment by simonbyrne** [comment]
- A distributed field is a regular field, on a distrbituted space.
- A distributed space is then a space on a distributed topology.
- field broadcasting, local operators (spectral/finite difference) will stay the same
- field reductions (`sum`, `maximum`, `norm`) etc, would need to do local reduction, then global reduction:
   - when to use `MPI_Reduce` vs `Allreduce`? would probably need both
   - Shared array would require synchronization
- diagnostics: will have certain additional requirements
- cross-element operators (dss / numerical flux) require communication

# Threading

Create some sort of way to partition broadcast expressions
```
threadthis() do thread_ctx
    @. thread_ctx dYc.ρθ = hdiv(hgrad(θ))
    @. thread_ctx dYc.ρuₕ = hdiv(hgrad(uₕ))
    @. thread_ctx dρw = hdiv(hgrad(w))
end
```
Ideally this would combine into multiple passes.

# DSS

currently:
 a. iterate over faces, levels: sum internal (non-vertex) nodes on opposing faces
 b. iterate over vertices, levels: sum over shared vertices

distributed:

- option 1: ghost elements (easiest, but somewhat wasteful)
   - `1:nrealelems` are the local
   - `nrealelems+1:ntotalelems` are ghost
   - `ntotalelems = nrealelems+nghostelems` 
   - iterators for each would probably be best.
  - can communicate whole elements initially
  - allocate fixed buffer size
  - 
- option 2: only ship boundaries
 a. copy faces to sendbuffer, performing any intermediate reductions
 b. should be able to keep send and receive buffer sizes symmetric

- who owns the exchange buffers?
  1.  Every distributed field gets buffer (MPIStateArray from ClimateMachine.jl)
  2. Owned by space: would need to manually specify number of fields
  3. Explicitly allocate buffer object and pass through to dss function.

overlap (can wait until later):
 a. start communication
 b. iterate interior & boundary faces / vertices
 c. finish communication
 d. iterate neighbour faces / vertices

**Comment by valeriabarra** [comment]
The only thing I would add is making sure that Operators can act on empty fields (not sure if this is already supported). It often happens that if a mesh is small (like a cube) and is distributed before refined elements are defined (e.g., by the warping function for a cubed-sphere) then you get some empty local field vectors, but your Operators should be able to do a no-op in that case

**Comment by simonbyrne** [comment]
DSS would use the following functions:
- `interior_faces` gives `(localelem, face, localopelem, opface, reversed)` for local faces only
- `ghost_faces` gives `(localelem, face, ghostelem, ghostface, reversed)` for ghost faces only
- `interior_vertices` gives a ragged array of `(localelem, vertex)` pairs for each unique vertex which are all local
- `ghost_vertices` gives a ragged array of `(isghost, elem, vertex)` triples for each unique vertex which touches a ghost face

**Comment by simonbyrne** [comment]
Next steps:
- [ ] Unit test: evaluate a tendency in both a distributed context and a non-distributed context, and check results are the same
- [ ] Solid body 2D sphere
- [ ] Extend to 3D
- [ ] Figure out a pattern to incorporate into drivers
- [ ] Copy to root rank
- [ ] .pvtu support in ClimaCoreVTK

**Comment by valeriabarra** [comment]
Should we probably add solid body/advection 2D & 3D test cases in a Cartesian domain as well?

**Comment by jakebolewski** [comment]
I don't think that is necessary to make progress, we can evaluate against the reference impl

**Comment by valeriabarra** [comment]
I think in general it is good to have (not necessarily related to this issue, but we can open the discussion in a new one). Especially for debugging the implicit solver as we mentioned today, we need simpler test cases. And it would also be a good test case to test different limiters and stabilization methods
