### ISSUE TITLE
Check energy conservation for rising bubble

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCore.jl#250]
PR #235 adds an energy plot for the rising bubble. There are a few issues left:

- The middle column seems to get unstable: is it ok with our current numerical scheme? Would increasing the hyperviscosity or using Smagorinsky SGS help?
- The energy is not conserved: Is the energy calculation correct? Should we expect it to be conserved with our numerics? Is the relative error acceptable? Would using the curl form help?

**Comment by jakebolewski** [comment]
@akshaysridhar I think this can be closed with your updates?

**Comment by szy21** [comment]
We'll probably need to do this again for the vector invariant form of the rising bubble (and some other test cases). We can either close it and open a new one when we need it, or keep it open and change the description. What do you think?

**Comment by jakebolewski** [comment]
I think we can close as these issues were specific to current impl.

**Comment by simonbyrne** [comment]
This is a plot of energy difference: 
![Energy difference plot](https://buildkite.com/organizations/clima/pipelines/climacore-ci/builds/408/jobs/ef45dbb4-a8c8-41aa-b994-b5e5affa413f/artifacts/6e4ec58c-763b-4358-b354-349e75249e4b)
