### ISSUE TITLE
Add support for paraview collections when working with time series

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#278]
See https://jipolanco.github.io/WriteVTK.jl/stable/metadata/paraview_collections/

**Comment by jakebolewski** [comment]
We probably want to start implementing a generic callback interface in ClimaCore which can be overloaded in ClimaCoreVTK to support this.

**Comment by simonbyrne** [comment]
Apparently there is also a JSON `.series` format: https://gitlab.kitware.com/paraview/paraview/blob/v5.5.0/Documentation/release/ParaView-5.5.0.md#json-based-new-meta-file-format-for-series-added

Because of course you should mix XML and JSON.

**Comment by jakebolewski** [comment]
Actually it makes sense as that allows them to support any file format extension supported by paraview
