### ISSUE TITLE
Better errors on broadcasting

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#28]
When broadcasting a function over a Field, and the function would always throw an error (e.g. due to an undefined variable), it will error out with "cannot infer concrete eltype":
https://github.com/CliMA/ClimateMachineCore.jl/blob/d7af0e3dfc89e7cfeb3a0edaa2b8c00e997df2bb/src/field/field.jl#L194

For regular arrays, Julia falls back on "type widening":
https://github.com/JuliaLang/julia/blob/5aca7a37be174ad9f4b28d3586ba9cc112c12d75/base/broadcast.jl#L925-L952
which would give a more useful runtime error. We currently can't do this as we don't support iteration over Fields, but we might want something similar, or a simpler variant e.g. just try to evaluate the first value.

**Comment by charleskawczynski** [comment]
I think #761 closes this!
