### ISSUE TITLE
Nested variables must be fields

### ISSUE THREAD

**Issue by kmdeck** [CliMA/ClimaCore.jl#303]
is it possible to add nested non-fields? Like:
```
y = [1.0, 2.0, 3.0]
z = (; :q => [1.0,2.0,3.0], :p => 2.0)
tmp = Fields.FieldVector(y = y, z = z)
```
? Right now, it seems like nested variables (like z.p, z.q) need to be Fields, like so:
```
julia> Y.soil
NamedTuple{(:ϑ_l, :θ_i), Tuple{Float64, Float64}}-valued Field:
  ϑ_l: [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4  …  0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
  θ_i: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0  …  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
```
I could see having non-fields being useful if a particular subcomponent (e.g. snow), which we would like to access via Y.snow.variable_1, Y.snow.variable_2..., doesnt require ClimaCore b/c we aren't solving PDEs for variable_1, variable_2. That said, I think all of our variables are associated with locations in space (though these spaces/domains don't always intersect - we'll have different spaces for different variables), so we could define a separate domain for each subcomponent as well, and then make each variable within that subcomponent a field.

The actual error comes from this:
```
julia> dy = similar(tmp)
ERROR: MethodError: no method matching similar(::NamedTuple{(:q, :p), Tuple{Vector{Float64}, Vector{Float64}}})
```

**Comment by simonbyrne** [comment]
@kmdeck can you try the latest version and see if that helps?

**Comment by kmdeck** [comment]
@simonbyrne it seems like it is working! thank you!
