### ISSUE TITLE
VTK output for sphere

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#356]
Functionality to add to VTK output:
- [x] Option to use data at cell centers (`VTKPointData`)
- [ ] On a sphere: option to reduce radius
- [x] Lat long plot: if using odd element numbers
   - move date-line elements to left or right
   - figure out what to do about polar point

**Comment by jakebolewski** [comment]
Are we just missing the ability to change the radius?

**Comment by simonbyrne** [comment]
And the lat-long plot

**Comment by jakebolewski** [comment]
MPAS tools vtk ouput: http://mpas-dev.github.io/MPAS-Tools/stable/visualization.html#lon-lat-coordinates

**Comment by jakebolewski** [comment]
Can this be closed?

**Comment by simonbyrne** [comment]
Yes, we didn't add an option to reduce the radius, but this is probably better done from inside paraview.

**Comment by jakebolewski** [comment]
I think so, we'll have to come up with a good way to attach extra metadata for each coordinate point (lat / long / level).
