### ISSUE TITLE
Plot vertical levels of a spherical shell

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#360]

**Comment by jakebolewski** [comment]
Is this different than https://github.com/CliMA/ClimaCore.jl/issues/354?  I was thinking to start just say `plot(sphere, level=N)` and go from there, we could also have a `Fields.level_field()` function that would return a horizontal shell field at a given level

**Comment by jakebolewski** [comment]
closed by #381

**Comment by valeriabarra** [comment]
Just dropping an example of a spherical level vtk output here for reference (baroclinic wave test case, level = 3, w component plotted, final simulation time)
![w_t_end_level_3](https://user-images.githubusercontent.com/39932030/148141626-2597ca45-ec5b-431c-8c35-d6ba86fff5c2.png)
