### ISSUE TITLE
How can we work with `NTuple` fields compactly?

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#38]
I've been playing around with the existing fields and it's not clear to me how to mutate `NTuple` fields. Here's an MWE:

```julia
import ClimaCore
const CC = ClimaCore
# bugfix
Base.length(space::CC.Spaces.FiniteDifferenceSpace) = length(CC.Spaces.coordinates_data(space))

FT = Float32
domain = CC.Domains.IntervalDomain(
    FT(0.0),
    FT(pi);
    x3boundary = (:left, :right),
);

mesh = CC.Meshes.IntervalMesh(domain; nelems = 16);
center_space = CC.Spaces.CenterFiniteDifferenceSpace(mesh);

n_tup = 2;

vals = (
   a = FT(0),
   nt = ntuple(n_tup) do i
       (x = FT(0),
       y = FT(0))
   end,
);

S = typeof(vals);

n_fields = Int(sizeof(vals)/sizeof(FT));

array = zeros(FT, length(center_space), n_fields);

cent_field = CC.Fields.Field(CC.DataLayouts.VF{S}(array), center_space);
```
EDIT: The above MWE was updated to work with recent changes

**Comment by simonbyrne** [comment]
`cent_field.nt.:1 .= 3` should work at the moment. We don't define `getindex`/`setindex!` on fields, so we could make `cent_field.nt[1] .= 3` also work.

**Comment by charleskawczynski** [comment]
`parent((cent_field.nt.:1).x) .= 3` seems to work.

**Comment by charleskawczynski** [comment]
Reopening this, since using `parent` like this is likely not what we want in the end, and there are too many places where this will be used (~115 variables, hundreds of functions). Ideally, o start using ClimaCore, we would have a syntax like:

```julia
cent_field.nt[1].x[k] # k is the k-th element along the altitude direction
```

**Comment by charleskawczynski** [comment]
cc @simonbyrne @jakebolewski

**Comment by charleskawczynski** [comment]
Related to #66.

**Comment by jakebolewski** [comment]
is the issue that since there is ~100+ variables it is not possible to give them unique names to be used in expressions?

**Comment by charleskawczynski** [comment]
Yeah, I'd say it's impractical.

**Comment by charleskawczynski** [comment]
It'll blow up the size/length of the kernels, and one major priority is to make them more compact.

**Comment by jakebolewski** [comment]
But you need to give them a unique name for netcdf right (following the schema), so I would assume that these variables all have a name -> index mapping under some ordering  and could be used interchangeably

**Comment by charleskawczynski** [comment]
I mean that it's not practical to do something like

```julia
var_parent = parent(var)
# and later use:
# var_parent[k] = 
# or
# var_k = var_parent[k]
```

**Comment by simonbyrne** [comment]
I think in this case it might be better to add an extra field to `PrognosticVariable` that contains the `Field` object, and `values` would then alias the underlying array.

**Comment by simonbyrne** [comment]
It may make sense to expose `getidx` from the finite difference operator as a concrete API (though we should perhaps rename it)

**Comment by simonbyrne** [comment]
Following discussion today, lets define `getindex` on columns.

**Comment by charleskawczynski** [comment]
Also,
```julia
setindex!(getproperty(cent_field.nt, 2).x, 3.0, 1)     # works, what we have
cent_field.nt[2].x[1] = 3.0                            # does not work, wish we had this
```
We can't use the `cent_field.nt.:2`, because we need `2` to be variable (`i`) and it seems like we can't interpolate this variable.

**Comment by charleskawczynski** [comment]
I think we can close this since we're now defining `getindex` for FiniteDifference fields in TC.
