### ISSUE TITLE
Consolidate all the `examples/` dependencies into a single env definition

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimaCore.jl#400]
They are practically all the same, so splitting them up doesn't buy anything and one env would be simpler for subpackage development.

**Comment by simonbyrne** [comment]
yep, and it's probably time to ditch the `LOAD_PATH` stuff as well...

**Comment by jakebolewski** [comment]
I'll do this as part of #397, it is causing all sorts of weird issues

**Comment by jakebolewski** [comment]
The only slightly annoying thing is that you have to `Pkg.develop` all the subpackages at once (because every develop does a full resolution of the dependencies).  Since this is only relevant to ex. setting up a fresh clone (and we could have a script that just setup up everything) I am not sure it is that big of a deal.

**Comment by jakebolewski** [comment]
closed by #397
