### ISSUE TITLE
Optimization-based limiters

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#403]
Implement element-local bounds-preserving limiters. Two limiters, one quasimonotone (OP1) and one sign-preserving (OP2) to prevent negative values of ρ, are defined in the reference paper Guba et al, "[Optimization-based limiters for the spectral element method](https://www.sciencedirect.com/science/article/pii/S0021999114001491?via%3Dihub)", JCP 2014. These limiters use a local element reconstruction, where quasimonotone and sign-preserving properties are defined with respect to the element nodal values (Gauss-Lobatto nodes). 

Each limiter defined in Guba et al. solves a constraint optimization problem completely local to each element (plus neighboring elements to determine suitable min/max bound constraints see Figure below). These are least squares optimization problems with equality and inequality constraints for the reconstructions.

To find the new time step limited quantity of interest (a tracer mixing ratio), `qⁿ⁺¹`, we first split a forward/explicit time step into 2 steps. (This algorithm works for any explicit RK scheme. If the bounds-preserving property is preferred, then can use a Strong Stability Preserving RK-SSP scheme.)

1. The first step finds an intermediate representation of the solution, denoted by `q*`, defined locally in each element (may not be continuous across elements). 
2. Then replace `q*` with a second intermediate approximation, denoted by `q**`. The simplest, least accurate `q**` can be the element average of `q*`. To find a better, higher-accurate approximation we want to find the optimal closest approximation of `q**` to `q*`, which requires solving a standard quadratic program (QP), where we minimize the quadratic objective function (i.e., least-square, density-weighted distance between `q*` and `q**`), subject to linear constraints. Hence, we construct the QP, by constraining `q**` by the the min/max of the quantity q, `qⁿₘᵢₙ` and ` qⁿₘₐₓ`, as given by the previous time step `n`, within the given element and its neighboring elements (i.e., over all nodal nodes in the stencil used to compute `∇q`).

![GubaEtAl2014Limiters](https://user-images.githubusercontent.com/39932030/148143490-64676524-5b0b-461d-ad2c-69a4b7bf3317.png)

Rough plan and current questions: 
- [x] 1. Define two different callbacks for the `ODEProblem`. One is a `stage_callback` applied at each RK stage (whose `rhs` function is not DSS'ed ?) and one is a `step_callback` applied at the end of each new (`n+1`) step (which includes the DSS step). 
- [x] 2. Call auxiliary functions for least squares optimization problems within ODE solver stage callback
    - [x] 2.a) Inside the auxiliary function, figure out the neighboring element values for min/max bounds
    - [x] 2.b) The QPs are given by eq. (37)-(40) in the ref paper (use `Quadprog.jl` ?)
    - [x] 2.c) To define the QP constraints, we need to preserve the mass of the quantity local to each element. We would need to define an element-wise integral function `sum(ρ)_e`, for element `e` (or perhaps, more simply, extract the Field values over elem `e`, `ρ_e`, and just use `sum(ρ_e)`).
 - [x] 3. Debug
 - [x] 4. Test and verify with advection problem on the 2D sphere with cosine bells, Gaussian hills, and slotted cylinders for tracer ICs with and without hyperdiffusion
 - [x] 5. Qualitative analysis: Plot tracers in lat-long grid and compare w/ paper results
 - [x] 6. Quantitative analysis: Compare tables and convergence rates w/ paper results

**Comment by valeriabarra** [comment]
Thanks for these pointers! I'm going to check OrdinaryDiffEq's limiter interface and how this Zhang-Shu limiter differs from the suggested one from Guba et al. (At a very first glance. Xhang-Shu seems to be formulated for DG and FV-WENO discretizations)

**Comment by valeriabarra** [comment]
But I can see how they used the stage callbacks. Thanks

**Comment by ranocha** [comment]
Yes, I think that should work. I added this limiter interface specifically for hyperbolic PDE discretizations. All explicit SSPRK methods should support them and many additional RK methods designed for hyperbolic PDEs, too. Feel free to ping me if anything is unclear.

**Comment by valeriabarra** [comment]
Okay, having looked at the OrdinaryDiffEqs docs and source code, as well as DiffEqCallbacks.jl's docs, and from the very useful [example](https://github.com/trixi-framework/Trixi.jl/blob/main/examples/tree_2d_dgsem/elixir_advection_callbacks.jl) on how to define new callbacks by the Trixi team, I think I have a clearer understanding of what we want to do. 

We most certainly want to set both the `stage_limiter!` and `step_limiter!`. My current understanding from the Guba paper is that `stage_limiter!` will not have the DSS internal call, while the `step_limiter!` will. We can group them (together with additional optional callbacks, like for viz and other queries) in a `CallbackSet` that is then passed to the `solve` call. Thanks again for the pointer and to the Trixi team for writing such a useful example!

**Comment by valeriabarra** [comment]
Skeleton started in this branch `valeria/opt-based-limiters`

**Comment by valeriabarra** [comment]
@simonbyrne for Point 2.c) above, would you agree that it would be easier to extract values of a Field `ρ` over an elem `e`, say `ρ_e`, and then simply find its integral using `sum(ρ_e)`, than overriding an element-wise `sum` method?

**Comment by valeriabarra** [comment]
For 2.b), would this [Quadprog](https://github.com/harmeling/Quadprog.jl) package be ok? I'm not sure if I can use it with our `Fields`, both scalar-valued and vector-valued fields

**Comment by valeriabarra** [comment]
Re 2.c), I've seen that Kiran implemented a `localelemindex` in #373 that we could use to restrict a `Field` over an element. But I'd like to discuss how to do this restriction

**Comment by simonbyrne** [comment]
> @simonbyrne for Point 2.c) above, would you agree that it would be easier to extract values of a Field `ρ` over an elem `e`, say `ρ_e`, and then simply find its integral using `sum(ρ_e)`, than overriding an element-wise `sum` method?

I think so: hopefully `sum(slab(field, e))` should work (but I'm not sure).

**Comment by simonbyrne** [comment]
> For 2.b), would this [Quadprog](https://github.com/harmeling/Quadprog.jl) package be ok? I'm not sure if I can use it with our `Fields`, both scalar-valued and vector-valued fields

Possibly? The easiest option initially is probably to pull out the underlying array (using `parent`). Once you get it to work, we can then try to figure out a nicer interface.

**Comment by jakebolewski** [comment]
since it is local to each element, they are solved independently and the problem is fairly small do you need a full blown ipsolver?  would it be possible to construct the linear system directly and do a fixed number of newton iterations?

**Comment by valeriabarra** [comment]
#446 takes care of 2.a)
