### ISSUE TITLE
Implict solver test broken with latest DiffEq

### ISSUE THREAD

**Issue by jakebolewski** [CliMA/ClimaCore.jl#409]
https://buildkite.com/clima/climacore-ci/builds/531#8be6ee1e-981d-4600-b3a7-620c0e28c997/96-101

We should probably pin the diffeq version as the internal API breaks often.

**Comment by jakebolewski** [comment]
Marked as known failure for the time being:
https://github.com/CliMA/ClimaCore.jl/pull/407/commits/eee71ee9ac626879afca0512735bdfd8068c6f5b

**Comment by simonbyrne** [comment]
Some discussion in https://github.com/CliMA/ClimaCore.jl/issues/41#issuecomment-1009485321

**Comment by jakebolewski** [comment]
This is also now impacting the diffeq unit test: https://github.com/CliMA/ClimaCore.jl/runs/4897621853?check_suite_focus=true#step:10:179

**Comment by charleskawczynski** [comment]
Closed by #1401
