### ISSUE TITLE
Should norms be non-dimensional?

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#474]
We're a bit inconsistent on how our norms on fields work: currently we use:
- l1 norm = ∑_i |x_i| * w_i * J_i ≈ ∫ |x| dΩ
- l2 norm = sqrt(∑_i |x_i|^2 * w_i * J_i) ≈ sqrt(∫ |x|^2 dΩ)
- linf norm = maximum_i |x_i| ≈ sup |x|

This implies that the dimensions are inconsistent across norms:
- l1 has units of x multiplied by the spatial unit (e.g. m^2 for 2D)
- l2 has units of x multiplied by the sqrt(spatial unit) (e.g. m for 2D)
- linf has units of x

To make these consistent, we could non-dimensionalize these by dividing by the same norm of a unit scalar, i.e.
- l1 norm = ∑_i |x_i| * w_i * J_i  /  ∑_i w_i * J_i ≈ ∫ |x| dΩ / ∫ 1 dΩ
- l2 norm = sqrt(∑_i |x_i|^2 * w_i * J_i /  ∑_i w_i * J_i ) ≈ sqrt(∫ |x|^2 dΩ / ∫ 1 dΩ)
- linf norm = maximum_i |x_i| ≈ sup |x|

**Comment by simonbyrne** [comment]
I think the consensus is that it should probably be the default, but should also be documented clearly.

**Comment by valeriabarra** [comment]
Yes, I think it's good to have them normalized or to support both. Perhaps with a different name, so to avoid confusion. And yes, +1 vote for clear documentation :)

**Comment by bischtob** [comment]
Perhaps we can also get a normalized integral to calculate means.
