### ISSUE TITLE
Update hyperdiffusion in Bickley jet and shallow water examples?

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#476]
Following from the discussion in the dycore meeting, it seems we need to change the hyperviscosity to apply to the tracer tracer proportion (theta) instead of the tracer density (rho theta).

**Comment by valeriabarra** [comment]
Thanks. I don't think it's needed in the shallow-water, since we apply it to the height function `h` alone there. But yes, we need to fix it in the Bickley jet examples
