### ISSUE TITLE
Add buildkite artifacts for perf monitoring

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#483]
It would be nice if we could click on urls in buildkite to view flame graphs.

In addition, we could add [cpuprofile assets](https://github.com/CliMA/ClimaCore.jl/pull/482#issuecomment-1023592217).

**Comment by jakebolewski** [comment]
Speedscope is probably the best "off the shelf" tool for this: https://github.com/jlfwong/speedscope#importing-via-url

but we might have to host the assets ourselves due to the cors issue (instead of buildkite)

**Comment by simonbyrne** [comment]
What's the easiest way to host this sort of stuff?

**Comment by jakebolewski** [comment]
cloud

**Comment by jakebolewski** [comment]
The cpuprofile files do work in speedscope:
![Screenshot from 2022-01-28 14-08-48](https://user-images.githubusercontent.com/1157798/151621760-3a73038d-fd79-4df1-b5ca-af6ccfa31bf8.png)

**Comment by simonbyrne** [comment]
Can we make a magic link: https://github.com/jlfwong/speedscope#importing-via-url

**Comment by simonbyrne** [comment]
oh, you already mentioned that!

**Comment by jakebolewski** [comment]
we could if we uploaded the assets somewhere else but  buildkite artifacts has a download link indirection

**Comment by jakebolewski** [comment]
is there some caltech resource we could use? these are quite small.  I'm happy to setup the google cloud account through the climatemachine.org domain but that would cost us some money.

**Comment by jakebolewski** [comment]
It also works with the firefox profiler which might be the best option.

* Can load from a url.
* Can upload local profiles and share a perma link: 

See: 
https://share.firefox.dev/3g6ImrP

**Comment by simonbyrne** [comment]
> is there some caltech resource we could use? these are quite small. I'm happy to setup the google cloud account through the climatemachine.org domain but that would cost us money.

Here are the options: https://www.imss.caltech.edu/services/web-hosting-development/web-hosting

It might be easier to do our own thing.

**Comment by jakebolewski** [comment]
Ok I'll set up the GCS bucket and direct all the billing questions to you lol.
