### ISSUE TITLE
Rename DataLayouts IJKFVH -> IJKCVH ?

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#514]
How outrageous is this at this point? :sweat_smile:

Thinking about improving our documentation and educational material (tutorials, examples, workshops, etc) a lot lately, and this discussion also arose in #507 , when writing documentation of math operators, we might want to draw the distinction between the `Field` as a function on a given space, and as a discrete set of discrete node values.
 
I think it is easy to describe the discrete set of node values by the indices we already chose and use in our DataLayouts, and to avoid any confusion, when writing documentation and docstrings (whenever this is not too cumbersome or already clear from context) we should attempt at using the same notation from the DataLayouts API. 

This being said, the DataLayouts module's docstring is a bit circular at the moment, in the sense that to describe the data associated to a Field (one might think the field itself can be called f) uses the letter `f` for field index or component. Should we switch to using `C` for component(s)?

Currently:
```
"""
    ClimaCore.DataLayouts

Notation:
- `i,j` are horizontal node indices within an element
- `k` is the vertical node index within an element
- `f` is the field index
- `v` is the vertical element index in a stack
- `h` is the element stack index

Data layout is specified by the order in which they appear, e.g. `IJKFVH`
indexes the underlying array as `[i,j,k,f,v,h]`
"""
```

Proposed: 
```
"""
    ClimaCore.DataLayouts

Notation:
- `i,j` are horizontal node indices within an element
- `k` is the vertical node index within an element
- `c` is the field component (1 if field is scalar, >1 if it is a vector field)
- `v` is the vertical element index in a stack
- `h` is the element stack index

Data layout is specified by the order in which they appear, e.g. `IJKCVH`
indexes the underlying array as `[i,j,k,c,v,h]`
"""
```

I know this would touch the code in a lot of places and it's probably not the right time (?) 
Here is an issue just to open up a discussion. Of course, it can be closed if people think it is not a good idea to keep

**Comment by simonbyrne** [comment]
I'm reluctant to change this: I don't think it adds that much for quite a lot of code change, and `f` for "field component" makes a certain amount of sense.

**Comment by valeriabarra** [comment]
It does, absolutely! And I can see why it was chosen. 
I was thinking in situations like the one that arose in the above mentioned docs PR, like if one wanted to explicitly denote the components. 
But it's good to avoid too many subscripts and cumbersome notation anyway. 
![image](https://user-images.githubusercontent.com/39932030/152621808-1419acd8-1c81-418a-820d-08d25a8dfbc8.png)

Feel free to close.
