### ISSUE TITLE
Are there any ClimaParameters envisioned for `src/`

### ISSUE THREAD

**Issue by odunbar** [CliMA/ClimaCore.jl#531]
Looking ahead, for packages that will depend on this. Are there going to be any ClimaParameters in `src/` or are they just appearing in examples?

If not, it may be worth thinking about (in future) whether we want to have a consistent API to other Clima packages that passes a `ClimaCoreParameters` object.

**Comment by simonbyrne** [comment]
I don't think in the package itself, but the examples can use them.

**Comment by charleskawczynski** [comment]
Can we close this?
