### ISSUE TITLE
Float32 support for GeneralizedExponentialStretching

### ISSUE THREAD

**Issue by akshaysridhar** [CliMA/ClimaCore.jl#560]
In https://github.com/CliMA/ClimaCore.jl/blob/main/src/Meshes/interval.jl, lines `176`, `196`, should we specify `FT` to secure the float-types ? I ran into this in ClimaAtmos, where `Float64` tests pass, but `Float32` tests don't since the `guess`es are promoted to Float64 leading to a method mismatch.  

```
    hₛsol = RootSolvers.find_zero(
        find_surface,
        RootSolvers.SecantMethod(guess₋, guess₊),  # < ------- Here, for instance
        RootSolvers.CompactSolution(),
        RootSolvers.ResidualTolerance(FT(1e-3)),
    )
```
@sriharshakandala Thanks for taking a quick look at this as well. 
cc @jakebolewski

**Comment by charleskawczynski** [comment]
It looks like [this](https://github.com/CliMA/ClimaCore.jl/blob/main/src/Meshes/interval.jl#L172-L173) will result in type promotions. Not sure if there are other places, though.

**Comment by akshaysridhar** [comment]
`RootSolvers.SecantMethod(FT(guess₋), FT(guess₊))` should be a reasonable fix right ? I can start the PR if this is the case @charleskawczynski

**Comment by akshaysridhar** [comment]
> It looks like [this](https://github.com/CliMA/ClimaCore.jl/blob/main/src/Meshes/interval.jl#L172-L173) will result in type promotions. Not sure if there are other places, though.

Yeah 4 instances of `log` functions to determine these guesses; tolerances have a secure type here, and I don't see this issue elsewhere in `Meshes`.

**Comment by charleskawczynski** [comment]
Yeah, that should work. If you wanted to stick to consistent floating point arithmetic, we'd probably want to change
```julia
    guess₋ = -dz_surface / zₜ / log(1 - (1 / (nelems - 1)))
    guess₊ = -dz_surface / zₜ / log(1 - (1 / (nelems + 1)))
```
to
```julia
    guess₋ = -dz_surface / zₜ / log(1 - FT(1 / (nelems - 1)))
    guess₊ = -dz_surface / zₜ / log(1 - FT(1 / (nelems + 1)))
```
