### ISSUE TITLE
Test horizontal limiters level-wise in a 3D Cartesian hybrid domain

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCore.jl#575]
Apply 2d spectral filter after horizontal advection; mimic what is done with tracer borrowing in Tempest and E3SM/CAM. Test in 3d domain (will not guarantee positivity without positivity preservation in vertical).

**Comment by valeriabarra** [comment]
I would rename this issue "Test horizontal limiters level-wise in a 3D hybrid domain", otherwise it can get confusing with a fully 3D limiting strategy. Thanks

**Comment by szy21** [comment]
> I would rename this issue "Test horizontal limiters level-wise in a 3D hybrid domain", otherwise it can get confusing with a fully 3D limiting strategy. Thanks

Thanks, I just renamed it. Please also feel free to change anything.

**Comment by valeriabarra** [comment]
Test with: 

- [ ] 2D x 1D Extruded Cartesian box domain 
- [ ] 2D x 1D Extruded sphere

**Comment by valeriabarra** [comment]
This is downstream of #584

**Comment by valeriabarra** [comment]
Blocking dependency: #586

**Comment by valeriabarra** [comment]
To be able to finalize the Cartesian hybrid 3d example, I need visualization functionality that we're currently missing #589

**Comment by valeriabarra** [comment]
Yes, and we will open a separate issue for that
