### ISSUE TITLE
Stability of Held Suarez with rho theta

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCore.jl#579]
Currently, Held Suarez crashes at around 400 days. The differences to tempest are:
- [x] Use hyperdiffusion for rho and rho theta
- [x] Use hyperdiffusion of w
- [ ] Use implicit vertical advection. Dependency: #555

**Comment by jiahe23** [comment]
Applying hyperdiffusion on rho and rho theta does not stabilize.

**Comment by szy21** [comment]
> isn't hyperdiff also applied on w in Tempest?

It is, but according to Oswald turning it off makes no difference. I have updated the issue to make it more clear.

**Comment by bischtob** [comment]
Yes, BUT in Tempest the vertical advection is apparently treated implicitly.

**Comment by szy21** [comment]
Yes, so I think it would be good to test the implicit vertical advection first. Do you think we should test the hyperdiffusion on w now?

**Comment by bischtob** [comment]
https://github.com/CliMA/ClimaCore.jl/pull/585

Please give it a full test.
