### ISSUE TITLE
CFL for hyperdiffusion is much smaller than 1

### ISSUE THREAD

**Issue by szy21** [CliMA/ClimaCore.jl#588]
For the Held-Suarez test case, with 4 elements and polynomial order 4, for a timestep of 400s, the largest hyperdiffusivity that doesn't break the simulation is 2e17. This suggests a CFL that is much smaller than 1.

**Comment by szy21** [comment]
With the same horizontal resolution and timestep, the largest hyperdiffusivity for the 3D deformation flow is also 2e17. For the barotropic instability it is 2.6e18. Tapio suggests trying hyperdiffusion + limiter on rho and the thermodynamic variable.

**Comment by szy21** [comment]
As discussed in the software and dycore meetings, it is very likely that different timestepping methods have very different stability regions. I'll leave the issue open for more discussion, but we are not investigating the problem now.

**Comment by valeriabarra** [comment]
I think we could close this, as this was probably due to the time stepper chosen and the fact that hyperdiffusion is non-monotonicity preserving, so the higher the hyperdiffusion coefficient, the more elem-to-elem oscillations you incite
