### ISSUE TITLE
ClimaCoreMakie tests: Using GLMakie

### ISSUE THREAD

**Issue by valeriabarra** [CliMA/ClimaCore.jl#607]
Hi, I am not sure why in the lib/ClimaCoreMakie/test/runtests.jl, on this [line](https://github.com/CliMA/ClimaCore.jl/blob/f8cb76988fed8a0d008d486b96c683d07c67c08c/lib/ClimaCoreMakie/test/runtests.jl#L8), we decided to load GLMakie and its namespace by including the `using GLMakie` statement only with the CI ENV variable. 

I tried to run these tests locally and they break, because later on, we call:

```
GLMakie.save(fig_png, fig)
```
Commenting the `if haskey(ENV, "CI")` statement tests run and work locally. So I wonder what is the way to run these locally. 
Thanks

**Comment by valeriabarra** [comment]
We don't have the same construct in the [ClimaCoreVTK unit tests](https://github.com/CliMA/ClimaCore.jl/blob/main/lib/ClimaCoreVTK/test/runtests.jl), and in fact, I can run them just fine locally

**Comment by valeriabarra** [comment]
And the same for the [ClimaCorePlots unit tests](https://github.com/CliMA/ClimaCore.jl/blob/main/lib/ClimaCorePlots/test/runtests.jl). 

So I am suspecting now the ClimaCoreMakie is the one with the unintended behavior.

**Comment by jakebolewski** [comment]
Makie can have different back-ends.

**Comment by valeriabarra** [comment]
The question was more about why we currently use that only in the case that `haskey(ENV, "CI")` rather than always (i.e., when one wants to run locally) and how to test locally otherwise.
