### ISSUE TITLE
out-of-memory kills hs on central

### ISSUE THREAD

**Issue by jiahe23** [CliMA/ClimaCore.jl#648]
This issue came up very recently (not a problem at the stage of #609 but a problem now).

With the setup of 
```
horizontal_mesh = cubed_sphere_mesh(; radius = R, h_elem = 4)
npoly = 4
z_max = FT(30e3)
z_elem = 10
t_end = FT(60 * 60 * 24 * 10)
dt = FT(400)
dt_save_to_sol = FT(60 * 60 * 24 * 10)
dt_save_to_disk = FT(60 * 60 * 24 * 10)
```

I requested 128G of mem and run into this error about every 300 simulation days. 

I used to request only 32G of mem and run with the same setup for at least 400 days without problem (right after #609 merged in).

**Comment by charleskawczynski** [comment]
@jiahe23, can you bisect through a bit more to see if more recent versions have this OOM error?

**Comment by jiahe23** [comment]
> @jiahe23, can you bisect through a bit more to see if more recent versions have this OOM error?

Sure, I'll start a new simulation with current main (with #647 in) and let you know.

**Comment by jiahe23** [comment]
No longer an issue at the current main (#647)
