### ISSUE TITLE
limiters should act on q, not rhoq

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#687]
I noticed the example:
https://github.com/CliMA/ClimaCore.jl/blob/6e2d89f47f7f78f2850e28f6f1875f204114ee21/examples/plane/limiters_advection.jl#L197-L214
we compute the min/max of rhoq, not q. This and the limiter code should be updated.

**Comment by valeriabarra** [comment]
Thanks for pointing this out!
I'll get to this after #674 is merged
