### ISSUE TITLE
Vertical integrals

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#693]
From @jiahe23:

> basically to compute sum_i (rho_q[i]) / sum_i (rho[i]) where q is the cloud water in the unit of kg/kg and rho is density, i represents the ith level

This should be waited by Jacobians to deal with mesh stretching.

**Comment by charleskawczynski** [comment]
This is what we added in TC:
```julia
function Base.cumsum(field::CC.Fields.FiniteDifferenceField)
    Base.cumsum(parent(CC.Fields.weighted_jacobian(field)) .* vec(field), dims = 1)
end
function Base.cumsum!(fieldout::CC.Fields.FiniteDifferenceField, fieldin::CC.Fields.FiniteDifferenceField)
    Base.cumsum!(fieldout, parent(CC.Fields.weighted_jacobian(fieldin)) .* vec(fieldin), dims = 1)
end
```
We didn't put it in ClimaCore since this is really only valid for `VF` data layouts. Also, I think `vertical_integral` would be a better name.

**Comment by simonbyrne** [comment]
The problem with `weighted_jacobian` in the general case is that it will include the GLL quadrature weights. we may need to rethink how we use weights.
