### ISSUE TITLE
Remapping for diagnostic output

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#742]
**Is your feature request related to a problem? Please describe.**

We need to be able to remap to a regular lat-long (RLL) mesh the diagnostic output at regular intervals.
- It needs to support distributed fields.
- It can use simple point-wise interpolation (e.g lagrange interpiolation to midpoints), rather than the conservative remapping.

**Describe the solution you'd like**

Initially something like this:
```julia
# a lightweight struct describing the rll mesh
rll_mesh = Meshes.RegularLatLongMesh(domain, nlat, nlong)

# this contains the distributed remap weights
# this would use `containing_element` and `reference_coordinates` to get the remap weights
https://github.com/CliMA/ClimaCore.jl/blob/main/src/Meshes/common.jl#L181-L199
remap_op = generate_midpoint_remap(rll_mesh, space)

# at each iteration
remap!(array, remap_op, input_field)
```

**Describe alternatives you've considered**

**Additional context**
Once we have that working, we can figure out how to tackle the distributed part: we would probably need some sort of distributed remap operator?

There is some code in ClimateMachine.jl that may be helpful here (under `src/Diagnostics`)

**Comment by jb-mackay** [comment]
@simonbyrne what is the needed format of the output here in order to plot?

**Comment by Sbozzolo** [comment]
This is now implemented
