### ISSUE TITLE
Standard data format

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#747]
## Purpose
We need a standard way to save data for restart and reanalysis, which is
 a. performant: there should be minimal conversion from in-memory format
 b. self-describing: it contains sufficient metadata to reload without access to the script and options used to generate it
 c. supports distributed fields: uses MPI I/O or some other distributed layer

Relevant issues:
- https://github.com/CliMA/ClimateMachine.jl/issues/114
- https://github.com/CliMA/ClimaCore.jl/issues/547

### Costs
- it will take some time to implement all possible backends, but we will initially focus on one
- although the container format is standard, the conventions are not the same as e.g. CF conventions. As a result, extra steps will be required to convert to tools which use this format.
- it is not compatible with the NetCDF CF conventions: this would require additional post-processing.

### Benefits
- saving data from distributed runs, using distributed I/O
- will allow us to read/write data in a single format for both restart and for post-processing
- we can potentially reduce memory consumption, by writing data without any intermediate copies
- make it possible to reload data after upgrading packages, as it won't serialize internals

### Risks
- C libraries which make use of parallel MPI I/O (HDF5, NetCDF, Adios2) need to be compiled for a particular MPI implementation.
- Future changes may mean that it is not possible to retain full backward compatibility. By adding the ClimaCore version to the file, we can hopefully reduce this risk.
- It may not be possible to support all features in each container format

## Producers

- Simon
- Sriharsha
- Ben

## Components

The main components will consist of
 - some sort of hierarchical container file: HDF5, NetCDF, Zarr, ADIOS2 BP: below we use the HDF5 naming convention of datasets, groups and attributes, but analogies to these exist in all of these formats.
 - a metadata and naming standard for representing the data in that file
 - code for saving/loading data in the relevant file format adhering to the standard

## Inputs
A description of the inputs to the solution (designs, references, equations, closures, discussions etc).

### Format description

Overall, the general principal of this design is to match the ClimaCore representation of spatial discretization internals wherever possible, make use of self-description features where possible (e.g. determine floating-point types from the container format instead of including it as an attribute), and only store what cannot be directly recomputed at load time.

The top level will consist of the following groups:
- `/domains`
- `/meshes`
- `/topologies`
- `/spaces`
- `/fields`
- `/timescales`

and the relevant data will be written to each group.

Not all container formats support references (e.g. Zarr), so in this case names can be used: the name should not include the top-level group name (e.g. a mesh should refer to a domain as `"earth"` not `"/domains/earth"`.

ClimaCore does not name objects (other than variable names, but these are not accessible from the object itself): some mechanim will be required to assign these. In most cases, users will use fields on a single space per file, so default names are provided for user convenience. If two distinct objects are attempted to be written with the same name, an error should be thrown.

#### Metadata

Metadata can be attached to the top-level attributes. Required attributes are:

- `version = "1"`
- `climacore_version`: version string from [PkgVersion.jl](https://github.com/KlausC/PkgVersion.jl)

#### Domains

Each domain will be stored as an subgroups under the `/domains` group:

  - `IntervalDomain` (default name: `"interval_x"`, `"intervaly"`): stored as an empty subgroup, with the following attributes
    - `type = "IntervalDomain"`
    - `coord_type`: one of `"XPoint"`, `"YPoint"`, `"ZPoint"`
    - `coord_min`: the floating point component of the value of `coord_min` field
    - `coord_max`:  the floating point component of the value of `coord_max` field
    - `boundary_names` (optional): if the `boundary_names` field is not `nothing`, it will be a vector of two strings

  - `SphereDomain`: (default name `"sphere"`) stored as an empty subgroup, with the following attributes
    - `type = "SphereDomain"`
    - `radius`: the value of the `radius` field

Note that no rectangle domain is required, as `RectilinearMesh` is stores as two `IntervalMesh`es.

#### Meshes

Each mesh will be stored as a subgroup under the `/meshes` group:

 - `IntervalMesh`: (default name same as domain) subgroup with the following attributes:
   - `type = "IntervalMesh"`
   - `domain`: reference (if supported by the container format) or name of the domain
   - `nelements` (optional): the number of elements if `faces` is a `Range` (i.e. the elements are equally space)

   and the following datasets:
   - `faces` (optional): the contents of `faces` if it is _not_ a `Range`. Note that these should be stored as a regular float array.

 - `RectilinearMesh`: (default name: `"rectilinear"`) empty subgroup with the following attributes:
   - `type = "RectilinearMesh"`
   - `domain`: either a reference (if supported by the container format) or the name of the domain
   - `interval1`/`interval2`: either a reference/name of the interval meshes.

 - `AbstractCubedSphere` (default name `"cubedsphere"`): empty subgroup with the following attributes:
   - `type`: type name of cubed sphere type
   - `domain`: reference/name of domain
   - `ne`: value of `ne` field

#### Topologies

Each topology will be stored as a subgroup under the `/topologies` group:

 - `IntervalTopology` (default name same as mesh): empty subgroup with the following attributes:
   - `type = "IntervalTopology"`
   - `mesh`: reference/name of domain

 - `Topology2D` (default name: `"topology2d"`): subgroup with the following attributes:
   - `type = "Topology2D"`
   - `mesh`: reference/name of domain

   and the following datasets:
   - `elemorder` (optional): if a non-default ordering is used (i.e. the `elemorder` field is not a `CartesianIndices`), this will be an integer matrix where the `i`th column contains the values in the `elemorder[i]` object.

_Note_: `DistributedTopology2D` will be stored as a `Topology2D` (i.e. the format should be agnostic to distribution).

#### Spaces

Each space will be stored as a subgroup under the `/spaces` group:

- `SpectralElementSpace1D`/`SpectralElementSpace2D` (default name `"horizontal_space"`)
  - `type`: one of `"SpectralElementSpace1D"`/`"SpectralElementSpace2D"`
  - `topology`: name/reference to topology
  - `quadrature_type`: `"GLL"` (or other type)
  - `quadrature_num_points`: value of `Nq`

- `FiniteDifferenceSpace` (default name `"vertical_space"`): we differ from the `ClimaCore` representation in that we don't specify face or center value here, but in the field itself. As such, it will be an empty group with
  - `type = "FiniteDifferenceSpace"`
  - `topology`: name/reference to topology

- `ExtrudedFiniteDifferenceSpace`: similar to `FiniteDifferenceSpace` (don't store face/center)
  - `type = "ExtrudedFiniteDifferenceSpace"`
  - `horizontal_space`: name/reference
  - `vertical_topology`: name/reference

In the case of terrain warped topologies, the group should also contain a dataset:
  - `zlevels`: the z heights of the faces, with attributes:
    - `data_layout: "VIJFH"` (or the name of the relevant datalayout type)

TODO: figure out how to handle topography

### Fields

A single `Field` can be stored as a dataset under `/fields`, or as a dataset under a `FieldVector` group (see below), and contains the underlying data array (i.e. `parent(field)`, along with the following attributes:
 - `type = "Field"`
 - `space`: a name/reference to the space
 - `location` (`FiniteDifferenceField`/`ExtrudedFiniteDifferenceField` only): `"cell"`/`"face"`
 - `data_layout`: a string of the type name of the data layour `"IJFH"`, etc.
 - `value_type`: the result of calling `string(eltype(field))`.
   - I would prefer a better approach to this, but this is probably easiest for now, assuming it can be parsed via `eval(Meta.parse(str))`?

A `FieldVector` will be stored as a group under `/fields` or another `FieldVector`, and have the following attributes set:
 - `type = "FieldVector"`

Components of the `FieldVector` will be represented as objects in the group, with field names determined by the name within that group. If a field appears multiple times, it can be stored as a reference.

In many cases, we will want to store a sequence of `Field`s over time. We do not yet have a representation for supporting this directly in `ClimaCore` (though it can be represented, somewhat inefficiently, as a solution object from `DiffEqBase`). Instead a dataset can be stored as a `FieldSeries`: this is stored identically to a `Field` but with an extra trailing dimension for time, and will have the following attributes:
- `type = "FieldSeries"`
- `timescale`: name/reference to time scale (see below)

#### Time scales

A time scale will be a 1d dataset under `/timescales`, default name will be `"default"`, containing the times at which a field is stored: typically these will be floats. Attributes (both optional):
- `units`: `"seconds"` / `"hours"` / `"days"`
- `epoch`: string of the date time in ISO8601 format (e.g. `2000-01-01T00:00:00`) corresponding which corresponds to time 0.

### Code

Code will go in an `IO` submodule of ClimaCore, and consist of "writers" and "readers".

#### Writers

Writers are used for writing data. Initially we will aim to support the following:

- `HDF5Writer`: this will write to HDF5 files. In a distributed setting, it will first gather to the root rank, then write from there.
- `HDF5ParallelWriter`: this will write to plain HDF5 files. It will require a parallel HDF5 build.
- Raw binary via MPI I/O. We would need some way to attach metadata:
  - one option is to write the data in a way such that it is a valid [Zarr directory store format](https://zarr.readthedocs.io/en/stable/spec/v2.html). This would require attaching the data as json
  - Should Zarr prove to complicated, we can define our own simplified metadata using a .toml file or similar.

The generic interface would be
```
write(writer[, name], object)
```
this would recursively create all necessary objects if they don't already exist.
  - to avoid creating duplicate spaces, meshes, etc, we will require some sort of cache to map non-field objects to their relevant name in the file. Ideally we would use a `WeakKeyDict`, but this would require all objects to be `mutable struct`s. Until then, we can just use a `Dict`, which will be fine as long as people don't create lots of different spaces in the same file.

In the case of `FieldSeries`, we will define an interface for writing time:
```
define_time_scale(writer[, timescale_name])
define_time_series(writer, name, field_prototype, timescale_name) # defines the object, but doesn't write data
```
Then writing a field would consist of
```
time_index = get_time_index(writer[, timescale], time) # an integer index into the timescale vector, creating if necessary
write(writer[, name], object, time_index)
```

#### Readers

Readers are used for reading data. Functionality would be similar to writers, with an interface
```
read_field(reader, name[; time])
```

An interface will be required for specifying the communication context and partitioning rule. These could be provided as additional arguments to a `read_topology` function.

Again, we would require some sort of cache `(comm, name) => object` to avoid creating duplicate spaces/meshes etc.

## Results and deliverables

The key aim is to be able to write and reload data for restart files in distributed ClimaAtmos runs.

## Task breakdown
- [x] #770
- [ ] A parallel reader/writer using HDF5.jl with parallel HDF5 library.
- [ ] A parallel reader/writer using MPI I/O.

## Reviewers

@sriharshakandala

**Comment by tapios** [comment]
I suggest to separate the requirements for restart files and diagnostics for post-processing (this is what you mean by reanalysis, right?). They have quite different requirements:
* A restart file needs to have a copy of the entire model state, without redundant quantities. Much of what you write above applies to this.
* A diagnostics file just needs the axes (space [e.g., lat, lon] and time) on which output fields are defined, and the relevant output fields. It is often advantageous--and for high-resolution simulations unavoidable--to write out redundant fields that in principle can be computed from the model state. On the other hand, details of how these fields are represented in ClimaCore are unimportant. 

Please have a look at how this is done in other models (e.g., GFDL, NCAR). (E.g., @szy21 knows GFDL.)

**Comment by szy21** [comment]
Yes, I would be happy to discuss with you about how this is done in GFDL models. I also think we should separate requirements for restart and “reanalysis”.

**Comment by simonbyrne** [comment]
> * A restart file needs to have a copy of the entire model state, on the model's native grid, without redundant quantities. Much of what you write above applies to this.

This is indeed the primary aim of this, but we should also be able to use it to load the data for post-processing.

**Comment by sriharshakandala** [comment]
Some items like Domain, mesh, etc. needs to be only saved in the first IO step (full field). 
Since we use a fixed grid, the rest of the field IO files can skip this information, except for the restart file!
One way is to write this domain, mesh and other information a different mesh file (i.e. separte mesh/domain and field data files).

**Comment by simonbyrne** [comment]
> Some items like Domain, mesh, etc. needs to be only saved in the first IO step.

Yes, that was my intention by splitting it up like this.

**Comment by sriharshakandala** [comment]
Do we plan to use parallel HDF5 or custom binary for diagnostics IO? One way is to write pointwise data so that it will be parallel and the full file can be assembled by separate postprocessing code!

**Comment by simonbyrne** [comment]
That will be a separate issue: for now I think we might do it by reducing to one rank, but we could support parallel I/O for that as well.

**Comment by sriharshakandala** [comment]
So, we will write diagnostic data to a NetCDF file from root, for the first pass!

**Comment by simonbyrne** [comment]
Yes.

**Comment by tapios** [comment]
We need a clearer statement of what the problem is that we want to solve here. I'm unclear on the goals of what is proposed. 

* We need restart files. We already have them in a rudimentary form. Is the issue here to have restart files for distributed simulations? If so, we should do the minimum needed to get the capabilities we need.
* We need diagnostics files. They are different from restart files. For example, we must have the capability to accumulate statistics on the fly, write them out on (lat, lon) grids (with height, pressure, or a stretched vertical coordinate in the vertical). Post-processing from instantaneous model dumps that are like restart files is unwieldy at best and will be unfeasible for higher-resolution runs. At the most abstract level, the model needs to be a black box that takes ClimaParameters in and outputs the statistics that we need for calibration.  The [Diagnostics in ClimateMachine](https://github.com/CliMA/ClimateMachine.jl/blob/9503cbc83eb098f0d92bef72745a1d214175940c/docs/src/HowToGuides/Diagnostics/UsingDiagnostics.md) were doing that, and were writing netCDF output (and we had gone through extensive iterations to get this right then). @LenkaNovak, @yairchn, Kiran and others had put a lot of work into this. We should maximize code re-use and minimize adaptations here to what is strictly necessary right now. To the extent we make changes, they should get us closer to being in compliance with [CMIP requirements](https://pcmdi.llnl.gov/CMIP6/Guide/modelers.html#4-model-output-fields). Model internals (e.g., how ClimaCore represents data) do not belong into these files.

While more perfection on file formats etc. may be desirable, right now we should focus on the minimum necessary to get the functionality we need. Other work (e.g., performance) is more important right now.

**Comment by szy21** [comment]
> * We need restart files. We already have them in a rudimentary form. Is the issue here to have restart files for distributed simulations? If so, we should do the minimum needed to get the capabilities we need.

Our restart files and diagnostic files are the same files now, maybe that's one of the confusion. The only difference is that we use the files directly for restarting and interpolate them offline to lat-lon netcdf for diagnosing.

**Comment by LenkaNovak** [comment]
@jb-mackay @simonbyrne please feel free to add to/ correct the following summary from yesterday's meeting:

**Restart Files**
- Optimal format: binary / hdf5 format is ok 
- Problem: Output by each MPI process separately requires the exact same MPI config needs to be used for further manipulation. 
- Feature to be added: ability to combine the raw restart files (both automatically and interactively) for restarts from different MPI config / debugging / additional diagnositics. We had an assembly script for the checkpoints (=restarts) in the [ClimateMachine](https://github.com/CliMA/ClimateMachine.jl/blob/9503cbc83eb098f0d92bef72745a1d214175940c/docs/src/DevDocs/ModelOutput.md) that I re-found after the meeting. Perhaps we can do something similar for the time being and then develop something more fancy and seamless (like what's proposed above) when we're at the optimization stage?  

**Basic Diagnostics Files**
- Format: NetCDF format following CF convention (CMIP requirement)
- Feature to be added: Fast linear interpolation (non-conservative) onto regular / Gaussian grids, similar to the `ClimateMachine.jl` machinery (most of which is already in `ClimaCore.jl` but may require some massaging to be consistent with the remapping operators) - @jb-mackay is already looking into this and is preparing the design issue. This will allow fast output for current development / showcase of the first results using the basic variables. 

**Refined Diagnostics Files**
- refining / extending the machinery of the basic diagnostics
- output variables should follow the CMIP requirements and [Yair's DiagnosticsMachine issue](https://github.com/CliMA/ClimateMachine.jl/issues/1596), and we will need to import / develop capabilities to interpolate to pressure levels, time accumulation etc (this should/will be addressed in a separate issue that we can take on).

**Comment by simonbyrne** [comment]
Thank you @LenkaNovak, that is correct. This proposal is a mechanism for storing the model state in a lossless manner. It is intended primarily for restart files, but can also be used to load the data interactively, for example if we want to identify the cause of a particular bug, or for custom post-processing analysis. The main challenge here is to describe the necessary metadata so that it can be correctly reconstructed in memory.

This is _not_ intended for default diagnostic output: that will continue to be in NetCDF format following CF conventions.

**Comment by yairchn** [comment]
Following the meeting, I did a quick search to recover some information regarding diagnostics in ClimateMachine:
This [issue](https://github.com/CliMA/ClimateMachine.jl/issues/1596) outlines what diagnostic types as spacial and temporal operations
A good list of variables to diagnose is found in the [docs](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/DiagnosticVariableList/) , this [PR](https://github.com/CliMA/ClimateMachine.jl/pull/508) and in this [issue](https://github.com/CliMA/ClimateMachine.jl/issues/214).

**Comment by yairchn** [comment]
To @tapios comment above I think maybe breaking this issue / task to distinct tasks that have clearer goal would help:
1. Restart: what fields are needed to restart the model and how and at what frequency are they stored?
2. IO: what model variables are saved at a lower temporal frequency?
3. Diagnostics fields: how and what statistics of the model state is computed and stored at high temporal frequency? 

The data format might change between these types (it might be that (1) and (2) are the same).

**Comment by simonbyrne** [comment]
As this is mostly complete, I'm going to close it. I'll create a new one for the remaining pieces.
