### ISSUE TITLE
Handling of fields on different spaces

### ISSUE THREAD

**Issue by simonbyrne** [CliMA/ClimaCore.jl#87]
When we have fields on different spaces (e.g. center and faces in a finite difference field), we currently use [`ArrayPartition` from RecursiveArrayTools.jl](https://github.com/SciML/RecursiveArrayTools.jl#arraypartition). The downside however is that you need to extract values via integer indices.

@ChrisRackauckas suggested [ComponentArrays.jl](https://github.com/jonniedie/ComponentArrays.jl), which lets you extract via names. We could also roll our own.

**Comment by jakebolewski** [comment]
Looking at ComponentArrays, I suspect we can come up with something fairly reduced by rolling our own but using similar ideas.

**Comment by simonbyrne** [comment]
One idea that occurred to me while trying to make the `Field` object work with the implicit solvers: maybe we should make this container object be "DiffEq-friendly", and use that instead of the increasingly large number of hacks that we have built up so far.
