### ISSUE TITLE
Add test for retrieving `dz` in LocalGeometry for different spaces

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/ClimaCore.jl#884]
One thing that we do, somewhat automatically but not very transparently in our finite difference stencils is extracting `dz` from the LocalGeometry. We should add a test, for clarity, how to do this in general. #883 implements this using `step = Geometry.LocalGeometry(space, idx, hidx).∂x∂ξ[1]`, and my main question / request is to add a test demonstrating that this is a valid `dz` for all spaces.

**Comment by Zhengyu-Huang** [comment]
I agree we need verify that, I changed  it to `step = Geometry.LocalGeometry(space, idx, hidx).∂x∂ξ[3, 3]`

**Comment by charleskawczynski** [comment]
Closed by #962.
